Unity-Technologies/com.unity.webrtc

Documentation~/index.md
Documentation~/jp/index.md
Documentation~/jp/tutorial.md

https://github.com/Unity-Technologies/UnityRenderStreaming/issues/161
Merge to the latest branch
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/163

doc: updated jp docs & jp images for https.md

---

Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/PeerConnectionTest.cs

- Add a callback `OnSignalingChange` to `RTCPeerConnection` class
- Add a test case to test callback

feat: add callback OnSignalingChange

---

.gitignore
.npmignore
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11Texture2D.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12Texture2D.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12Texture2D.h
Plugin~/WebRTCPlugin/GraphicsDevice/GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/IGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/ITexture2D.h
Plugin~/WebRTCPlugin/NvEncoder.cpp
Plugin~/WebRTCPlugin/NvEncoder.h
Plugin~/WebRTCPlugin/UnityEncoder.h
Plugin~/WebRTCPlugin/UnityVideoCapturer.cpp
Plugin~/WebRTCPlugin/UnityVideoCapturer.h
Plugin~/WebRTCPlugin/WebRTCPlugin.vcxproj
Plugin~/WebRTCPlugin/pch.h

Use D3D11.1 as an intermediate between DX12 and NVEncode

chore: preparing to support Directx12

---

CHANGELOG.md
package.json

Preparing QA for version 1.1.0
- fixed changelog
- changed `package.json` to change the package version
- update Linux plugin

chore: change version 1.1.0

---

Plugin~/README.md
Plugin~/README_EN.md
README.md

- fixed roadmap
- added doc how to build plugin on Linux

doc: fixed readme

---

.yamato/upm-ci-webrtc-packages.yml

fix: fix build package process

---

Samples~/DataChannel.unity
Samples~/MediaStream.unity
Samples~/MediaStreamSample.cs
Samples~/PeerConnection.unity

Update sample scenes for Unity2019.3
Add Unit Test for sample scenes

fixed: Update WebRTC package sample

---

Runtime/Unity.WebRTC.Runtime.asmdef
Tests/Runtime/Unity.WebRTC.RuntimeTests.asmdef

https://github.com/Unity-Technologies/UnityRenderStreaming/issues/200

chore: disable build settings for non-supported platforms

---

.yamato/upm-ci-libwebrtc.yml
.yamato/upm-ci-publish-github-release.yml
.yamato/upm-ci-webrtc-packages.yml
BuildScripts~/build_libwebrtc_linux.sh
BuildScripts~/build_libwebrtc_macos.sh
BuildScripts~/build_libwebrtc_win.cmd
Plugin~/WebRTCPlugin/WebRTCPlugin.vcxproj
Plugin~/WebRTCPluginTest/WebRTCPluginTest.vcxproj

- Add build parameter `rtc_use_h264` to avoid patent issue
- Update windows instance image
- Remove `jsoncpp.lib`

fix: Remove h.264 dependencies

---

BuildScripts~/build_plugin.sh
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderCuda.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderD3D11.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderD3D12.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderGL.cpp

Fix this issue https://github.com/Unity-Technologies/UnityRenderStreaming/issues/239

Fix Color bug using OpenGL Encoder

---

Tests/Runtime/AudioTest.cs
Tests/Runtime/AudioTest.cs.meta

Add unit-test of `Audio` class to make increase coverge of testing

test: Add unit-test of Audio class

---

Runtime/Scripts/WebRTC.cs
WebRTC~/Packages/manifest.json
WebRTC~/ProjectSettings/ProjectVersion.txt

OpenGL api not support on Windows / Mac.
So, I stop playing on that time.

chore: stop playing if using not support graphics api

---

Runtime/Scripts/RTCPeerConnection.cs

fix: remove warning

---

CHANGELOG.md
Documentation~/index.md
Documentation~/jp/index.md
README.md
WebRTC~/Packages/com.unity.webrtc/package.json
package.json

The destination of this PR is `release/2.0.0` branch.
Merge this change to `develop` branch too after merged this PR.

chore: upgrade version 2.0.0-preview

---

Tests/Runtime/PeerConnectionTest.cs

This PR is related to the issue user reported.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/17
`OnIceCandidate` callback is not called if the peer isn't added a track or a data channel.

test: Add testcase for peerconnection

---

.yamato/meta/environments.yml
.yamato/upm-ci-libwebrtc.yml
BuildScripts~/build_libwebrtc_linux.sh
BuildScripts~/build_libwebrtc_macos.sh
BuildScripts~/build_libwebrtc_win.cmd
BuildScripts~/build_plugin.cmd
BuildScripts~/build_plugin.sh
BuildScripts~/build_plugin_mac.sh
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/SetSessionDescriptionObserver.cpp
Plugin~/WebRTCPlugin/SetSessionDescriptionObserver.h
Plugin~/WebRTCPlugin/UnityVideoDecoderFactory.cpp
Plugin~/WebRTCPlugin/UnityVideoDecoderFactory.h
Plugin~/WebRTCPlugin/UnityVideoEncoderFactory.cpp
Plugin~/WebRTCPlugin/VideoCaptureTrackSource.cpp
Plugin~/WebRTCPlugin/VideoCapturer.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.h
Plugin~/WebRTCPlugin/WebRTCPlugin.vcxproj
Plugin~/WebRTCPlugin/pch.h
Plugin~/WebRTCPluginTest/WebRTCPluginTest.vcxproj
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.AsyncOperation.cs
Runtime/Scripts/WebRTC.cs
Samples~/MediaStreamSample.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/NativeAPITest.cs

- update libwebrtc to m83
- released libwebrtc on github : https://github.com/Unity-Technologies/com.unity.webrtc/releases/tag/M83
- change RTCError struct and set RTCError on failure  f580261
- Add UnityVideoDecoder for Test 7f711d1

Update libwebrtc m83

---

Editor/PeerListView.cs
Editor/PeerStatsView.cs
Editor/WebRTCInternals.cs
Runtime/Scripts/WebRTC.cs

compatible webrtc-internal dump file
Export dumpfile to Assets/dump.json

feat: stats dump

---

.yamato/upm-ci-webrtc-packages.yml

We have gotten the error below on yamato.
so it will be fixed by this change.
```
[05:16:48.898 INF] Process exited
[05:16:50.940 INF] 
################################### Running next command ###################################
unzip -qq -o macos_plugin* 
############################################################################################
[05:16:50.957 INF] Starting process on subprocess runner
[05:16:50.984 INF] Process exited
[05:16:50.985 INF] unzip:  cannot find or open macos_plugin*, macos_plugin*.zip or macos_plugin*.ZIP.
```

fix: fixed pack error on yamato

---

Plugin~/WebRTCPlugin/CMakeLists.txt
Plugin~/WebRTCPluginTest/CMakeLists.txt

Edited cmake file to import .editorconfig

chore: Add .editorconfig

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.h
Plugin~/WebRTCPlugin/PeerConnectionStatsCollectorCallback.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/Context.cs
Runtime/Scripts/IntPtrExtension.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/RTCStats.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/MediaStreamTest.cs

- Added test for `RTCRtpSender.GetStats` and `RTCRtpSender.GetStats`
- Refactor IntPtrExtension

test: Add GetStats test

---

Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.h
Plugin~/WebRTCPluginTest/GraphicsDeviceTest.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.h

This change is for corresponding the native test of d3d12 graphics API.

test: Add d3d12 native test

---

.yamato/promotion.yml
.yamato/upm-ci-webrtc-packages.yml
CHANGELOG.md
WebRTC~/Packages/com.unity.webrtc/package.json
WebRTC~/Packages/manifest.json
WebRTC~/ProjectSettings/ProjectVersion.txt
package.json

- changed unity editor version 2019.4
- upgrade package version 2.1.0-preview

chore: upgrade version

---

.yamato/upm-ci-webrtc-packages.yml
Editor/PeerStatsView.cs
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Runtime/Scripts/RTCStats.cs
Samples~/StatsSample.cs
Tests/Runtime/MediaStreamTest.cs

This changes to fix the bugs of unittest on Linux
The cause of failure was it has no enough time to collect statistics.

test: fixed unittest bugs

---

Runtime/Scripts/RTCRtpReceiver.cs
Runtime/Scripts/RTCRtpReceiver.cs.meta
Runtime/Scripts/RTCRtpSender.cs
Runtime/Scripts/RTCRtpSender.cs.meta
Runtime/Scripts/WebRTC.cs

Two CS files are added.
- `RTCRtpReceiver.cs`
- `RTCRtpSender.cs`

refactor: Split the code into separate files

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.h
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs
Samples~/MediaStreamSample.cs

issue: https://github.com/Unity-Technologies/com.unity.webrtc/issues/138
fix point only this commit https://github.com/Unity-Technologies/com.unity.webrtc/commit/4e659ff2ac961611cfca1c0baa71634970620036
- need enable video offer option falg
others
- add get signaling state method 
- add sdp type about rollback

fix: media stream sample

---

Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/MediaStreamTrackTest.cs
Tests/Runtime/MediaStreamTrackTest.cs.meta
Tests/Runtime/PeerConnectionTest.cs
Tests/Runtime/SignalingPeers.cs
Tests/Runtime/SignalingPeers.cs.meta
Tests/Runtime/StatsCheck.cs
Tests/Runtime/StatsCheck.cs.meta

This is requesting two changes.
1. Three CS files are added to reduce code size of `MediaSteramTest.cs`.
- `SignalingPeers.cs`
- `StatsCheck.cs`
- `MediaStreamTrackTest.cs`
2. Add a test case **OnAddTrackDelegatesWithEvent** to check the operation of the delegate `MediaStream.OnAddTrack` and `MediaStream.OnRemoveTrack` .

refactor: refactor test code

---

Documentation~/en/install.md
Documentation~/en/videostreaming.md
Documentation~/jp/install.md
WebRTC~/Packages/manifest.json
WebRTC~/Packages/packages-lock.json

- Add documents for `RTCRtpSender.SetParameter`
- Fix documentation broken layout
- Add `packages-lock.json `

doc: add documents for setparameter

---

Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs

The issue reported on Unity Forum.
[#429](https://forum.unity.com/threads/unity-render-streaming-introduction-faq.742481/page-9#post-6251790)
This issue can be checked as the compile error on Rider.
I am not sure why it is contained in the code, anyway, I removed them. 😅

fix: remove ZWSP(zero-width-space)

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/RTCStats.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/MediaStreamTrackTest.cs
Tests/Runtime/PeerConnectionTest.cs

- fix an assertion about using mutex
- fix an assertion when access an undefined object of `RTCStats`

fix: Fixed crash when using the debug build plugin

---

Documentation~/index.md
README.md

related issue
https://github.com/Unity-Technologies/com.unity.webrtc/issues/202

doc: fix broken link

---

Samples~/MultiplePeerConnections.unity
Samples~/MultiplePeerConnections.unity.meta
Samples~/MultiplePeerConnectionsSample.cs
Samples~/MultiplePeerConnectionsSample.cs.meta
Samples~/MungeSDP.unity
Samples~/MungeSDP.unity.meta
Samples~/MungeSDPSample.cs
Samples~/MungeSDPSample.cs.meta

I add two samples (MultiplePeerConnections/MungeSDP)
- refered: https://webrtc.github.io/samples/src/content/peerconnection/multiple/
- refered: https://webrtc.github.io/samples/src/content/peerconnection/munge-sdp/

feat: add sample(MultiplePeerConnections/MungeSDP)

---

Samples~/MultiVideoReceive.unity
Samples~/MultiVideoReceive.unity.meta
Samples~/MultiVideoReceiveSample.cs
Samples~/MultiVideoReceiveSample.cs.meta

Sample of sending multiple VideoTracks through a single `PeerConnection`.
Press the `AddTransciver` button will increase the number of videos you receive.

add: multivideo receive sample

---

Runtime/Scripts/VideoStreamTrack.cs
Samples~/MultiplePeerConnectionsSample.cs
Samples~/MungeSDPSample.cs
Samples~/VideoReceiveSample.cs
Tests/Runtime/VideoReceiveTest.cs

- change `VideoStreamTrack.InitializeReceiver` method to can specify rendering resolution.

feat: change initializereceiver can specify resolution

---

Documentation~/videostreaming.md

- add video receiving document on `videostreaming.md`

doc: vedeoreceive document

---

Documentation~/index.md

Related issue https://github.com/Unity-Technologies/com.unity.webrtc/issues/199

doc: Add description of the graphics driver vesion.

---

Tests/Runtime/AudioTest.cs
Tests/Runtime/ContextTest.cs
Tests/Runtime/DataChannelTest.cs

Related issue. https://github.com/Unity-Technologies/com.unity.webrtc/issues/199

test: Fix test code to pass the runtime test on the virtual machine like parallels desktop

---

Samples~/Stats/StatsSample.cs

I think this cause of the issue might be this changes (#237).

fix: fixed exception error in StatsSample

---

Samples~/Bandwidth.meta
Samples~/Bandwidth/Bandwidth.unity
Samples~/Bandwidth/Bandwidth.unity.meta
Samples~/Bandwidth/BandwidthSample.cs
Samples~/Bandwidth/BandwidthSample.cs.meta

This PR adds a sample to demonstrate changing bandwidth dynamically.
This sample references the official webrtc sample written javascript.
https://webrtc.github.io/samples/src/content/peerconnection/bandwidth/

feat: bandwidth sample

---

Documentation~/install.md

Fixed this issue.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/246

doc: fixed doc to install package

---

Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Tests/Runtime/PeerConnectionTest.cs

fix for the issue.
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/343

fix: Fix peer connection constructor crash bug

---

Samples~/ChangeCodecs.meta
Samples~/ChangeCodecs/ChangeCodecs.unity
Samples~/ChangeCodecs/ChangeCodecs.unity.meta
Samples~/ChangeCodecs/ChangeCodecsSample.cs
Samples~/ChangeCodecs/ChangeCodecsSample.cs.meta

This is a sample scene to demonstrate the codec selection feature.
For this sample, Developers can understand easily how to implement the codec selection.

feat: add "ChangeCodec" sample

---

.yamato/upm-ci-webrtc-packages.yml
Tests/Runtime/PeerConnectionTest.cs

- Update native plugins 
- add a workaround to avoid errors on CI testing
- Fixed bugs of the CI script

chore: Fix CI yaml file

---

.yamato/upm-ci-webrtc-packages.yml
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/DataChannelObject.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.h
Runtime/Scripts/Context.cs
Runtime/Scripts/Internal/Marshalling.cs
Runtime/Scripts/RTCDataChannel.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs
Samples~/DataChannel/DataChannelSample.cs
Samples~/MediaStream/MediaStreamSample.cs
Samples~/PeerConnection/PeerConnectionSample.cs
Samples~/Stats/StatsSample.cs
Tests/Runtime/ContextTest.cs
Tests/Runtime/DataChannelTest.cs
Tests/Runtime/NativeAPITest.cs
Tests/Runtime/PeerConnectionTest.cs
Tests/Runtime/SignalingPeers.cs

Related issues #265, #281
`RTCDataChannel` constructor throws an exception caused by the options. It is when be set along with `RTCDataChannelInit.maxRetransmits` and `RTCDataChannelInit.maxPacketLifeTime`.  Cannot be set along with `maxRetransmits` and `maxPacketLifeTime`.
The `options` parameter for the constructor method becomes optional.
```
var channel = new RTCDataChannel("dc");
```
- `Protocol`
- `MaxRetransmits`
- `MaxRetransmitTime`
- `Ordered`
- `BufferedAmount`
- `Negotiated`

fix: Fixed RTCDataChannel constructor 

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/RTCIceCandidate.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs
Samples~/TrickleIce.meta
Samples~/TrickleIce/Line.prefab
Samples~/TrickleIce/Line.prefab.meta
Samples~/TrickleIce/Option.prefab
Samples~/TrickleIce/Option.prefab.meta
Samples~/TrickleIce/TrickleIce.unity
Samples~/TrickleIce/TrickleIce.unity.meta
Samples~/TrickleIce/TrickleIceSample.cs
Samples~/TrickleIce/TrickleIceSample.cs.meta
Tests/Runtime/IceCandidateTest.cs
Tests/Runtime/PeerConnectionTest.cs

This pull request adds the sample to understand the usage of IceCandidate properties.
This is an original tricleIce example.
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

feat: Add TrickleIce sample

---

Samples~/DataChannel/DataChannelSample.cs

https://github.com/Unity-Technologies/com.unity.webrtc/issues/292

fix: fix typo

---

Runtime/Scripts/AudioStreamTrack.cs

Allow setting of audio track label

---

Documentation~/videostreaming.md

* Minor proposal (semantic issue on line 100)

Minor proposal (line 151)

---

.yamato/upm-ci-webrtc-packages.yml
BuildScripts~/build_plugin_android.sh
BuildScripts~/test_plugin_android.sh

Added jobs for building Android plugin but these jobs have not been triggered automatically yet.

chore: Added Android plugin build process into CI

---

.yamato/meta/environments.yml
.yamato/upm-ci-libwebrtc.yml
BuildScripts~/build_libwebrtc_android.sh
BuildScripts~/build_libwebrtc_ios.sh
BuildScripts~/build_libwebrtc_linux.sh
BuildScripts~/build_libwebrtc_macos.sh
BuildScripts~/build_libwebrtc_win.cmd
BuildScripts~/patches/generate_licenses.patch

- upgrade libwebrtc m89
- fix generated license proces
- fix error on windows build

chore: libwebrtc m89

---

.yamato/upm-ci-webrtc-packages.yml
BuildScripts~/build_libwebrtc_linux.sh
BuildScripts~/build_plugin_linux.sh
BuildScripts~/test_plugin_linux.sh
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.h
Plugin~/WebRTCPluginTest/CMakeLists.txt
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.cpp

- we need add `is_asan=true islsan=true` on `gn` command for building `libwebrtc` if using sanitizer.
- and update `Clang` version to 10.

fix: link sanitize option

---

Editor/BuildProcessor.cs
Editor/BuildProcessor.cs.meta

Check the build settings previous building Android app.
- AndroidMinSdkVersion > 21
- AndroidArchitecture == ARM64

feat: Check minsdkversion and target architectures when building apps for android platform

---

Samples~/Bandwidth/BandwidthSample.cs
Samples~/ChangeCodecs/ChangeCodecsSample.cs
Samples~/DataChannel/DataChannelSample.cs
Samples~/MediaStream/MediaStreamSample.cs
Samples~/Menu/Menu.unity
Samples~/MultiVideoReceive/MultiVideoReceiveSample.cs
Samples~/MultiplePeerConnections/MultiplePeerConnectionsSample.cs
Samples~/MungeSDP/MungeSDPSample.cs
Samples~/PeerConnection/PeerConnectionSample.cs
Samples~/Scripts/SceneSelectUI.cs
Samples~/Stats/StatsSample.cs
Samples~/TrickleIce/TrickleIceSample.cs
Samples~/VideoReceive/VideoReceiveSample.cs

feat: Add toggle on sample menu to enable hardware codec

---

BuildScripts~/build_plugin_ios.sh
BuildScripts~/build_plugin_mac.sh
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/Context.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/RTCRtpSender.cs
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Samples~/Menu/Menu.unity
Samples~/PerfectNegotiation.meta
Samples~/PerfectNegotiation/PerfectNegotiation.unity
Samples~/PerfectNegotiation/PerfectNegotiation.unity.meta
Samples~/PerfectNegotiation/PerfectNegotiationSample.cs
Samples~/PerfectNegotiation/PerfectNegotiationSample.cs.meta
Samples~/Scripts/SceneSelectUI.cs
WebRTC~/ProjectSettings/EditorBuildSettings.asset

ref https://webrtc.github.io/samples/src/content/peerconnection/perfect-negotiation/

Feat: perfectnegotiation sample

---

Samples~/MultiVideoReceive/MultiVideoReceive.unity
Samples~/MultiVideoReceive/MultiVideoReceiveSample.cs

https://user-images.githubusercontent.com/26959415/115813467-2f109980-a42e-11eb-926c-9f0ae7aade48.mp4
possible to increase the number of cameras dynamically

chore: improve multi video receive sample

---

Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Samples~/Bandwidth/BandwidthSample.cs
Samples~/ChangeCodecs/ChangeCodecsSample.cs
Samples~/DataChannel/DataChannelSample.cs
Samples~/MediaStream/MediaStreamSample.cs
Samples~/Menu/Menu.unity
Samples~/MultiVideoReceive/MultiVideoReceiveSample.cs
Samples~/MultiplePeerConnections/MultiplePeerConnectionsSample.cs
Samples~/MungeSDP/MungeSDPSample.cs
Samples~/PeerConnection/PeerConnectionSample.cs
Samples~/PerfectNegotiation/PerfectNegotiationSample.cs
Samples~/Scripts/SceneSelectUI.cs
Samples~/Stats/StatsSample.cs
Samples~/TrickleIce/TrickleIceSample.cs
Samples~/VideoReceive/VideoReceiveSample.cs
Tests/Runtime/ConditionalIgnore.cs
Tests/Runtime/MediaStreamTrackTest.cs
Tests/Runtime/TestHelper.cs
Tests/Runtime/VideoReceiveTest.cs

Some android crash when smaller than 114 width or height.

fix: limit minimum texturesize

---

Samples~/Menu/Menu.unity
Samples~/Scripts/SceneSelectUI.cs

Changed how to connect between button events and callbacks. This way should be more flexible and fewer defects than before.

refactor: Fix menu scene in sample

---

Runtime/Scripts/WebRTC.cs

Fix this issue.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/393

fix: Fix color space for Vulkan API

---

Runtime/Scripts/VideoStreamTrack.cs
Samples~/Bandwidth/BandwidthSample.cs
Samples~/MultiVideoReceive/MultiVideoReceiveSample.cs
Samples~/MultiplePeerConnections/MultiplePeerConnections.unity
Samples~/MungeSDP/MungeSDPSample.cs
Samples~/PeerConnection/PeerConnectionSample.cs
Samples~/Stats/Stats.unity
Samples~/Stats/StatsSample.cs
Tests/Runtime/MediaStreamTrackTest.cs

- `Camera.CaptureStreamTrack` method throws exception when using the argument width (or height) is zero
- Remove warning logs in the `BandWidth` scene
- Fix the UI layout of `MultiplePeerConnection` and `Stats` scene

fix: Fix sample bugs

---

Runtime/Scripts/WebRTC.AsyncOperation.cs
Samples~/Bandwidth/Bandwidth.unity
Samples~/ChangeCodecs/ChangeCodecsSample.cs
Samples~/MultiVideoReceive/MultiVideoReceiveSample.cs
Samples~/TrickleIce/TrickleIce.unity
Samples~/TrickleIce/TrickleIceSample.cs

Fixed the issue that the text of **candidate pool size** is not changed when changing the value.

fix Fixed candidatePoolSize

---

Runtime/Scripts/WebRTC.cs
Samples~/VideoReceive/VideoReceive.unity
Samples~/VideoReceive/VideoReceiveSample.cs
Tests/Editor/SetScriptingDefineSymbolsForTest.cs
Tests/Editor/SetScriptingDefineSymbolsForTest.cs.meta
Tests/Runtime/WebRTCTest.cs
WebRTC~/ProjectSettings/ProjectSettings.asset

- ignore legacy graphics format on validation
- add cameraUsageDescription for test WebCamTexture
- add usewebcam toggle on videoreceive sample
- add dropdownlist about webcam devices

fix: webcamtex graphicsformat validation

---

Tests/Runtime/WebRTCTest.cs

fix: webrtc test to private

---

Plugin~/WebRTCPlugin/Context.cpp
Runtime/Scripts/WebRTC.cs

closed #417 #418 #419 and renamed flag to enableDtlsSrtp

added enableDtlsSrtp flag

---

Editor/BuildProcessor.cs

Fix this issue.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/448

fix: Fix the issue on Unity2021

---

Samples~/Menu/Menu.unity
Samples~/MultiAudioReceive.meta
Samples~/MultiAudioReceive/AudioObject.prefab
Samples~/MultiAudioReceive/AudioObject.prefab.meta
Samples~/MultiAudioReceive/MultiAudioReceive.unity
Samples~/MultiAudioReceive/MultiAudioReceive.unity.meta
Samples~/MultiAudioReceive/MultiAudioReceiveSample.cs
Samples~/MultiAudioReceive/MultiAudioReceiveSample.cs.meta
Samples~/Scripts/SceneSelectUI.cs
WebRTC~/ProjectSettings/EditorBuildSettings.asset

- Add MultiAudioReceive Sample
- Source audio is selected by Random from sourceAudioClips on inspector.

feat:MultiAudioReceiveSample

---

Editor/MediaSourceGraphView.cs
Editor/PeerStatsView.cs
Runtime/Scripts/RTCStats.cs
Samples~/Stats/Stats.unity
Samples~/Stats/StatsSample.cs
Tests/Runtime/PeerConnectionTest.cs
Tests/Runtime/StatsCheck.cs

- Add RTCAudio/VideoSourceStats class
- Fix stats view about MediaSourceStats
- Add Audio/VideoStreamTrack on StatsSample
- Add AudioTrack to GetStatsReturnsReport Test

Fix:RTCStats about Audio

---

Plugin~/WebRTCPlugin/UnityAudioTrackSource.cpp
Plugin~/WebRTCPlugin/UnityAudioTrackSource.h
Samples~/MultiplePeerConnections/MultiplePeerConnections.unity
Samples~/MultiplePeerConnections/MultiplePeerConnectionsSample.cs

- add AudioTrack source on MultiplePeersSample

feat: add AudioTrack source on MultiplePeersSample

---

Plugin~/WebRTCPlugin/Context.cpp

to follow webrtc thread model:
https://groups.google.com/g/discuss-webrtc/c/vCfnjG-wxoc

add destruct of audio device and move into worker thread

---

Plugin~/WebRTCPluginTest/ContextTest.cpp
Runtime/Plugins/macOS/webrtc.bundle/Contents/Info.plist
Samples~/VideoReceive/VideoReceive.unity
Samples~/VideoReceive/VideoReceiveSample.cs

- add audio track source on `VideoReceiveSample`
- add checkbox and dropdown about Microphone

feat: add audio track on video receive sample

---

Samples~/Audio/Audio.unity
Samples~/Audio/AudioSample.cs

test: Add UI of the Audio sample to check the effects of the audio bandwidth parameter

---

Plugin~/WebRTCPlugin/DummyAudioDevice.cpp
Runtime/Scripts/AudioStreamTrack.cs

I've found short sections repeating or dropping when receiving and playing audio.
I corrected the part I thought was the cause, and it works good in my computer.
I think that @karasusan is currently refactoring the relevant parts.
I hope my poor edits are helpful.

Fixed an unstable audio data receiving and playing process

---

Plugin~/WebRTCPlugin/UnityAudioTrackSource.cpp
Plugin~/WebRTCPlugin/UnityAudioTrackSource.h
Samples~/Audio/AudioSample.cs
Samples~/VideoReceive/VideoReceiveSample.cs

- Fixed crash bug when disposing the audio track
- Reduce the audio latency of the microphone

fix: Fix Audio sample bug

---

Samples~/Audio/Audio.unity
Samples~/Audio/AudioSample.cs
WebRTC~/ProjectSettings/AudioManager.asset

The DSP buffer size setting affects the audio latency, so I added the UI to select options.

fix: Add UI to select DSP buffer size option in Audio sample

---

Samples~/Bandwidth/BandwidthSample.cs
Samples~/ChangeCodecs/ChangeCodecsSample.cs
Samples~/PeerConnection/PeerConnectionSample.cs

this fix is workaround.
When the Track sent from RemotePeer was added to the Local MediaStream, a crash occurred in the Callback of `OnRemoveTrack` when removing Track from Stream.
The transmitted Track is created by libwebrtc, and it is a plugin, and there is no reference in the plugin.
Therefore, when Remove Track is performed on the Sender side and Negotiation occurs, the instance in libwebrtc is destroyed.
Therefore, there is an s crash in the Callback of `OnRemoveTrack` in the receiving Media Stream.
For the received track, it is necessary to match the lifespan on the Manage side and in the Plugin.

fix: crash samples use receive stream

---

Documentation~/index.md

https://github.com/Unity-Technologies/com.unity.webrtc/issues/442

doc: Add note about building android platform

---

Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/AudioStreamTrack.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs
Samples~/MultiAudioReceive/MultiAudioReceive.unity
Samples~/MultiAudioReceive/MultiAudioReceiveSample.cs
Tests/Runtime/AudioStreamTrackTest.cs
Tests/Runtime/NativeAPITest.cs
Tests/Runtime/PeerConnectionTest.cs
Tests/Runtime/SignalingPeers.cs

Sometimes audio streaming is received audio as a monoral channel even if sending the stereo.
This reason that the first few frames of audio are received as a monoral from the webrtc library.
This fix is ignoring the first few frames to get the right number of channels when receiving the audio streaming data.

fix: Audio channel count 

---

Plugin~/README.md

doc: Added 7zip requirement to Plugin readme

---

Tests/Runtime/DataChannelTest.cs
Tests/Runtime/SignalingPeers.cs

Added the testcase for this PR #522.

test: Add testcase for executable sync context

---

Plugin~/WebRTCPlugin/CMakeLists.txt
Plugin~/WebRTCPlugin/UnityLogStream.cpp
Plugin~/WebRTCPlugin/UnityLogStream.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/WebRTC.cs
Tests/Runtime/ContextTest.cs
Tests/Runtime/NativeAPITest.cs

[Feature] add enable native flag when Initializing webRTC

---

Samples~/PeerConnection/PeerConnection.unity
Samples~/PeerConnection/PeerConnectionSample.cs

fix: Add protocol option UI in PeerConnection sample

---

.yamato/meta/environments.yml
.yamato/upm-ci-libwebrtc.yml
BuildScripts~/build_libwebrtc_android.sh
BuildScripts~/build_libwebrtc_ios.sh
BuildScripts~/build_libwebrtc_linux.sh
BuildScripts~/build_libwebrtc_macos.sh
BuildScripts~/build_libwebrtc_win.cmd
BuildScripts~/build_plugin_android.sh
BuildScripts~/build_plugin_ios.sh
BuildScripts~/build_plugin_linux.sh
BuildScripts~/build_plugin_mac.sh
BuildScripts~/build_plugin_win.cmd
BuildScripts~/test_plugin_android.sh
BuildScripts~/test_plugin_ios.sh
BuildScripts~/test_plugin_linux.sh
BuildScripts~/test_plugin_mac.sh
BuildScripts~/test_plugin_win.cmd
Editor/InboundRTPStreamGraphView.cs
Editor/OutboundRTPStreamGraphView.cs
Editor/PeerStatsView.cs
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/pch.h
Runtime/Scripts/RTCStats.cs
Samples~/Audio/AudioSample.cs
Samples~/Bandwidth/BandwidthSample.cs
Tests/Runtime/StatsCheck.cs

Upgrade libwebrtc M92.
https://groups.google.com/g/discuss-webrtc/c/hks5zneZJbo/m/Z-p4AfCrCQAJ
It should be available for developing some features like this.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/535

feat: Upgrade libwebrtc m92

---

.yamato/upm-ci-webrtc-packages.yml
Plugin~/WebRTCPlugin/DummyAudioDevice.h
Tests/Runtime/VideoReceiveTest.cs
Tests/Runtime/WebRTCTest.cs

fix: fixed compile error caused by updating libwebrtc

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/UnityVideoRenderer.cpp
Plugin~/WebRTCPlugin/UnityVideoRenderer.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.h
Plugin~/WebRTCPluginTest/ContextTest.cpp
Plugin~/WebRTCPluginTest/VideoRendererTest.cpp
Runtime/Scripts/Context.cs
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Samples~/Bandwidth/BandwidthSample.cs
Samples~/ChangeCodecs/ChangeCodecsSample.cs
Samples~/MultiVideoReceive/MultiVideoReceiveSample.cs
Samples~/MultiplePeerConnections/MultiplePeerConnectionsSample.cs
Samples~/MungeSDP/MungeSDPSample.cs
Samples~/PeerConnection/PeerConnectionSample.cs
Samples~/PerfectNegotiation/PerfectNegotiationSample.cs
Samples~/VideoReceive/VideoReceiveSample.cs
Tests/Runtime/NativeAPITest.cs
Tests/Runtime/VideoReceiveTest.cs

Issue https://github.com/Unity-Technologies/com.unity.webrtc/issues/507

feat: Implement video frame resize callback

---

Samples~/Bandwidth/Bandwidth.unity
Samples~/Bandwidth/BandwidthSample.cs

**Scale Resolution Down** option is for testing the behavior of `VideoStreamTrack` when changing the parameter [RTCRtpEncoderParameter.scaleResolutionDownBy](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpEncodingParameters/scaleResolutionDownBy).
https://user-images.githubusercontent.com/1132081/147335029-33374e90-b62b-447b-981e-ac58c0309290.mp4

fix: Add "scale resolution down" option into Bandwidth sample

---

.yamato/upm-ci-webrtc-packages.yml
BuildScripts~/build_plugin_win.cmd
Plugin~/CMakeLists.txt
Plugin~/README.md
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp

This pull request changes the compiler for windows native plugin MSVC to Clang.
You need to install Clang compiler on Visual Studio installer. Please see [MSDN](https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170) to install.
CMake can make Visual Studio project using clang. Add only command option `-T ClangCL` option.
```
cmake . -G "Visual Studio 16 2019" -A x64 -B "build64" -T ClangCL
```

 chore: Use clang for building windows plugin

---

Runtime/Scripts/VideoStreamTrack.cs

- Add need flip flag on `VideoStreamTrack` constructor 
- This pr is to fix https://github.com/Unity-Technologies/UnityRenderStreaming/issues/597

feat: Add a flag on VideoStreamTrack constructor to flip sending texture vertically 

---

Runtime/Scripts/AudioStreamTrack.cs

This PR fixes this issue.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/548

fix: Fix a bug that sending stereo audio produces mono clip on some peers

---

Samples~/ChangeCodecs/ChangeCodecsSample.cs

Sometimes there is no target report, so check before accessing.

Fix: Check target stats count on ChangeCodecsSample

---

Plugin~/WebRTCPlugin/AudioTrackSinkAdapter.cpp
Plugin~/WebRTCPlugin/AudioTrackSinkAdapter.h
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/UnityAudioTrackSource.cpp
Plugin~/WebRTCPlugin/UnityAudioTrackSource.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.h
Runtime/Scripts/AudioStreamTrack.cs
Runtime/Scripts/Context.cs
Runtime/Scripts/WebRTC.cs
Samples~/Audio/AudioSpectrumView.cs
Tests/Runtime/AudioStreamTrackTest.cs
Tests/Runtime/ContextTest.cs

This pull request is for refactoring `AudioStreamReceiver`, which is `AudioStreamTrack` internal class.
This change makes clear the ownership about the audio rendering process in `AudioStreamTrack` class.
Please note that this change is not solved known issues, but only refactoring.

refactor: Refactor AudioStreamReceiver class that the class has a own native pointer

---

Plugin~/WebRTCPlugin/DummyAudioDevice.cpp
Plugin~/WebRTCPlugin/DummyAudioDevice.h
Runtime/Scripts/AudioStreamTrack.cs
Tests/Runtime/AudioStreamTrackTest.cs

This is a hot fix for crash bug about `AudioStreamTrack`.
This change is contained in #627 made by @aet.

fix: RemoveSink method must be called before removing AudioTrackSink

---

.gitignore
Plugin~/.clang-format

We introduce clang-format as a C++ code formatter. We will apply formatter to our code gradually.

chore: Add clang-format file

---

Plugin~/WebRTCPluginTest/CMakeLists.txt
Plugin~/WebRTCPluginTest/UnityVideoDecoderFactoryTest.cpp
Plugin~/WebRTCPluginTest/UnityVideoEncoderFactoryTest.cpp

This pull request adds native test for `UnityVideoDecoderFactory` class and `UnityVideoEncoderFactory` class.

test: Add testcase for video encoder/decoder factory

---

Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.h
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/ICudaDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.h
Plugin~/WebRTCPluginTest/NvCodec/CudaDeviceTest.cpp

Refactor `CudaContext` class and fix the method name.

refactor: Refactor CudaContext class

---

Plugin~/WebRTCPlugin/Codec/NvCodec/CMakeLists.txt
Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvDecoderImpl.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvDecoderImpl.h
Plugin~/WebRTCPlugin/UnityVideoDecoderFactory.cpp
Plugin~/WebRTCPlugin/UnityVideoDecoderFactory.h
Plugin~/WebRTCPlugin/pch.h
Plugin~/WebRTCPluginTest/NvCodec/CMakeLists.txt
Plugin~/WebRTCPluginTest/NvCodec/NvCodecTest.cpp
Plugin~/WebRTCPluginTest/NvCodec/NvDecoderImplTest.cpp
Plugin~/WebRTCPluginTest/VideoCodecTest.cpp
Plugin~/WebRTCPluginTest/VideoCodecTest.h

- Support H264 Decoder using NvDecoder
- Add Encode/Decode native test
Todo
- Check working on Vulkan
- future: Support other input format

feat: NvDecoder (H264) for DirectX11

---

BuildScripts~/build_plugin_win.cmd
Plugin~/CMakePresets.json

**CMakePresets.json** is a recent feature of CMake since 3.20.
Microsoft team wrote the article for the new feature here.
https://devblogs.microsoft.com/cppblog/cmake-presets-integration-in-visual-studio-and-visual-studio-code/

chore: Add CMakePresets.json to support several IDEs

---

Runtime/Scripts/AudioCustomFilter.cs
Runtime/Scripts/AudioStreamTrack.cs
Samples~/Audio/Audio.unity
Samples~/Audio/AudioSample.cs
Samples~/VideoReceive/VideoReceiveSample.cs

- add loopback flag on `AudioStreamTrack`
- If True, Send audio input to remote and Play audio in local.
- If False, only send to remote. Not play audio in local.
#637

fix: Add mute flag on AudioCustomFilter

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.h

https://github.com/Unity-Technologies/com.unity.webrtc/issues/703

fix: Fix NvEncoderImpl::SetRates is called a lot

---

CHANGELOG.md
Samples~/ReplaceTrack/ReplaceTrackSample.cs
WebRTC~/Packages/packages-lock.json
WebRTC~/ProjectSettings/ProjectVersion.txt

chore: Update Unity Editor version of sample project

---

Plugin~/WebRTCPlugin/Codec/H264ProfileLevelId.cpp
Plugin~/WebRTCPlugin/Codec/H264ProfileLevelId.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.h
Plugin~/WebRTCPluginTest/H264ProfileLevelIdTest.cpp
Samples~/Bandwidth/BandwidthSample.cs

capping max framerate calculate by h264 profile level

fix : Fix check h264 support framerate condition

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
Documentation~/install.md
README.md
package.json

This pull-request is for promoting the package to the **pre-release** status.

chore: Promote pre-release version 2.4.0-pre.1

---

.yamato/upm-ci-webrtc-packages.yml
CHANGELOG.md
LICENSE.md
Runtime/AssemblyInfo.cs
Runtime/Scripts/AudioStreamTrack.cs
Runtime/Scripts/MediaStream.cs
Runtime/Scripts/MediaStreamTrack.cs
Runtime/Scripts/RTCDataChannel.cs
Runtime/Scripts/RTCIceCandidate.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/RTCRtpReceiver.cs
Runtime/Scripts/RTCRtpSender.cs
Runtime/Scripts/RTCRtpTransceiver.cs
Runtime/Scripts/RTCStats.cs
Runtime/Scripts/RTPParameters.cs
Runtime/Scripts/RefCountedObject.cs
Runtime/Scripts/RenderTextureDepth.cs
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.AsyncOperation.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/ContextTest.cs
ValidationExceptions.json
ValidationExceptions.json.meta

- Fix API document to pass the package validation.
- Fix LICENSE file to follow the rule of the validation.
- Add ValidationExceptions.json to suppress warnings and errors of the package validation.
- Keep some APIs private that APIs don't need public.

fix: Fix errors and warnings reported from package validation suite

---

.yamato/upm-ci-webrtc-packages.yml

This pull request change the name of the default branch to run auto test when making new PRs.
I will delete the **develop** branch after merge this.

chore: Change default branch name

---

.yamato/upm-ci-publish-github-release.yml

see https://github.com/cli/cli/blob/trunk/docs/install_linux.md

chore: Update github-cli GPG signing key

---

.yamato/upm-ci-webrtc-packages.yml

Added the environment variable to create a package with a valid signature during APV testing.
https://github.com/Unity-Technologies/Graphics/pull/5923

chore: Package Signature on CI

---

.yamato/upm-ci-webrtc-packages.yml
BuildScripts~/format-plugin.sh
Plugin~/.cmake-format
Plugin~/CMakeLists.txt
Plugin~/NvCodec/CMakeLists.txt
Plugin~/NvCodec/implib/CMakeLists.txt
Plugin~/WebRTCPlugin/Android/CMakeLists.txt
Plugin~/WebRTCPlugin/CMakeLists.txt
Plugin~/WebRTCPlugin/Codec/CMakeLists.txt
Plugin~/WebRTCPlugin/Codec/NvCodec/CMakeLists.txt
Plugin~/WebRTCPlugin/GraphicsDevice/CMakeLists.txt
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CMakeLists.txt
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/CMakeLists.txt
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/CMakeLists.txt
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/CMakeLists.txt
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/CMakeLists.txt
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/implib/CMakeLists.txt
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/CMakeLists.txt
Plugin~/WebRTCPluginTest/CMakeLists.txt
Plugin~/WebRTCPluginTest/NvCodec/CMakeLists.txt

[cmake-format](https://github.com/cheshirekow/cmake_format) is a command for formatting CMakeLists.txt nicely.

chore: Add cmake-format file to check code format of CMakeLists.txt 

---

.yamato/compile-package.yml
.yamato/package.metafile
.yamato/verification.yml

- Add job to check compilation managed code
- Fix verification job for applying job dependencies

ci: Fix CI jobs to check compilation managed code

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
Documentation~/install.md
Documentation~/requirements.md
Documentation~/tutorial.md
Documentation~/videostreaming.md
Plugin~/README.md
README.md
ValidationExceptions.json
WebRTC~/Packages/packages-lock.json
WebRTC~/ProjectSettings/ProjectVersion.txt
package.json

Changed package version for next release.
- Change Unity Editor version of sample project
- Fix documentaion

chore: Update package version 3.0.0-pre.2

---

.yamato/format.yml
.yamato/nativeplugin.yml
.yamato/package.metafile
.yamato/upm-ci-webrtc-packages.yml

This pull request separates files which are for CI jobs. Because we need to add jobs to test the package on many platforms more and more in future.

ci: Refactor CI process code

---

.yamato/coverage.yml
.yamato/upm-ci-webrtc-packages.yml

This PR is for refactoring CI code.

ci: Create coverage.yml file to separate CI jobs for calculating coverage 

---

Editor/PeerStatsView.cs
Samples~/Stats/StatsSample.cs

`RTCStats.Id` property returns unreadable string after updating libwebrtc (https://github.com/Unity-Technologies/com.unity.webrtc/pull/843). 
So this pull request fixes the text to identify RTCStats. 
In this pull request fixed two parts of the project.
- RTCStats sample
- WebRTC Stats window

fix: Display readable RTCStats name in sample scene

---

Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/Internal/Marshalling.cs
Runtime/Scripts/RTCRtpReceiver.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/SignalingPeers.cs
Tests/Runtime/TransceiverTest.cs

Add two methods to `RTCRtpReceiver` class.
```
RTCRtpContributingSource[] GetSynchronizationSources();
RTCRtpContributingSource[] GetContributingSources();
```

feat: Add GetContributingSources in RTCRtpReceiver class

---

.yamato/nativeplugin.yml
.yamato/upm-ci-libwebrtc.yml
.yamato/upm-ci-webrtc-packages.yml
Plugin~/NvCodec/CMakeLists.txt
Plugin~/NvCodec/NvCodec/NvDecoder/NvDecoder.cpp
Plugin~/NvCodec/NvCodec/NvDecoder/NvDecoder.h
Plugin~/NvCodec/NvCodec/NvEncoder/NvEncoder.cpp
Plugin~/NvCodec/NvCodec/NvEncoder/NvEncoder.h
Plugin~/NvCodec/NvCodec/NvEncoder/NvEncoderCuda.cpp
Plugin~/NvCodec/NvCodec/NvEncoder/NvEncoderCuda.h
Plugin~/NvCodec/Utils/BitDepth.cu
Plugin~/NvCodec/Utils/ColorSpace.cu
Plugin~/NvCodec/Utils/FFmpegDemuxer.h
Plugin~/NvCodec/Utils/FFmpegStreamer.h
Plugin~/NvCodec/Utils/Logger.h
Plugin~/NvCodec/Utils/NvCodecUtils.h
Plugin~/NvCodec/Utils/NvEncoderCLIOptions.h
Plugin~/NvCodec/Utils/Resize.cu
Plugin~/NvCodec/Utils/crc.cu
Plugin~/NvCodec/include/cuviddec.h
Plugin~/NvCodec/include/nvEncodeAPI.h
Plugin~/NvCodec/include/nvcuvid.h

Require installing drivers below.
- NVIDIA Windows display driver [522.25](https://www.nvidia.com/download/driverResults.aspx/193713/en-us/) or [newer](https://www.nvidia.com/Download/index.aspx?lang=en-us)
- NVIDIA Linux display driver [520.56.06](https://www.nvidia.com/download/driverResults.aspx/193764/en-us/) or [newer](https://www.nvidia.com/Download/index.aspx?lang=en-us)

feat: Upgrade NVIDIA Codec SDK 12.0

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp

This PR fixes this issue.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/882

fix: Add NV_ENC_PIC_FLAG_OUTPUT_SPSPPS flag

---

BuildScripts~/format-plugin.sh
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalDevice.mm
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.mm
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalTexture2D.mm

Format Objective-C++ files with clang-format as well, no functional changes

Chore: Add .mm files to clang-format

---

Runtime/Scripts/AudioCustomFilter.cs
Runtime/Scripts/AudioStreamTrack.cs

#920 this issue related this PR.
**AudioStreamTrack.onReceived** delegate is able to fetch audio buffers from another peer. It makes available to create a cusom audio receiver.

feat: Add event AudioStreamTrack.onReceived  

---

Samples~/VideoReceive/VideoReceiveSample.cs

Since Unity 2022.1, WebCamTexture.graphicsFormat returns R8G8B8A8_SRGB on Android Vulkan. WebRTC doesn't support this graphics format when using Vulkan, and throw exception.
To make workaround, created another texture and copy texture in every frame to convert graphics format whch is supported by WebRTC package.

fix: Fix the issue that video streaming doesn't work from camera device on Android

---

Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/PeerConnectionTest.cs

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/canTrickleIceCandidates

feat: Add RTCPeerConnection.CanTrickleIceCandidates

---

Plugin~/NvCodec/README.txt
Plugin~/WebRTCPlugin/Codec/NvCodec/NvDecoderImpl.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.h
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.h
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/GpuMemoryBufferCudaHandle.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/GpuMemoryBufferCudaHandle.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceContainer.h

Refactored to consolidate CUDA handle generation for all Graphics APIs in one place.

refactor: Refactor CUDA handle

---

Plugin~/NvCodec/Utils/ResizeSurf.cu

Finished testing of using #930 vs my previous implementation using NPP and noticed a small regression.
- It seems scaleResolutionDownBy = 1.5 doesn't quite work, trivial casting issue
- ~~The image quality is a bit blurry, so I added a lanczos alternative and image quality is now comparable to what I've been using with NPP~~ EDIT: Kernel worked in local testing, but don't have time to debug an issue when running on cloud. For now, I'll just fallback to my old NPP scaling code in internal use

fix: fractional scaling ratio support

---

Plugin~/WebRTCPlugin/GpuMemoryBuffer.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/IGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/UnityVulkanInitCallback.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanTexture2D.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanTexture2D.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanUtility.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanUtility.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/WebRTCMacros.h
Plugin~/WebRTCPluginTest/GraphicsDeviceContainer.cpp

This PR is reopening the previous one #888 .
I'm checking platforms (Windows, Ubuntu, Android) on my devices.
- ✔️ Windows10 2023.1.8f1
- ✔️ Ubuntu 20.04 2022.3.6f1
@aet,  @BrianHarrisonUnity
I will be glad if you check it again.

fix: Use IUnityGraphicsVulkan::CommandRecordingState for commandbuffer

---

.yamato/package.metafile
BuildScripts~/build_libwebrtc_android.sh
BuildScripts~/build_libwebrtc_ios.sh
BuildScripts~/build_libwebrtc_linux.sh
BuildScripts~/build_libwebrtc_macos.sh
BuildScripts~/build_libwebrtc_win.cmd
BuildScripts~/build_plugin_android.sh
BuildScripts~/build_plugin_ios.sh
BuildScripts~/build_plugin_linux.sh
BuildScripts~/build_plugin_mac.sh
BuildScripts~/build_plugin_win.cmd
BuildScripts~/build_testrunner_android.sh
BuildScripts~/build_testrunner_linux.sh
BuildScripts~/build_testrunner_mac.sh
BuildScripts~/build_testrunner_win.cmd
BuildScripts~/patches/README.md
BuildScripts~/patches/add_jsoncpp.patch
BuildScripts~/patches/fix_task_queue_base.patch
BuildScripts~/test_plugin_android.sh
BuildScripts~/test_plugin_ios.sh
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPluginTest/FrameGenerator.h
Plugin~/WebRTCPluginTest/VideoFrameSchedulerTest.cpp
Runtime/Scripts/RTCStats.cs
Tests/Runtime/StatsReportTest.cs

This PR upgrades the version of **libwebrtc** from [M112](https://groups.google.com/g/discuss-webrtc/c/V-XFau9W9gY) to [M115](https://groups.google.com/g/discuss-webrtc/c/1CTKFxJsrmQ/m/2v_RuAJdAAAJ).

feat: Upgrade libwebrtc M115

---

Runtime/Scripts/AudioCustomFilter.cs

```
private static void Test1()
{
InitData(out var data);
var sw = Stopwatch.StartNew();
for (int i = 0; i < data.Length; i++)
{
data[i] = 0;
}
sw.Stop();
Debug.Log($"test1: {sw.ElapsedMilliseconds}"); //About 50
}
private static void Test2()
{
InitData(out var data);
var sw = Stopwatch.StartNew();
Array.Clear(data, 0, data.Length);
sw.Stop();
Debug.Log($"test2: {sw.ElapsedMilliseconds}");//About 30
}
private static void InitData(out float[] data)
{
data = new float[100_000_000];
UnityEngine.Random.InitState(1);
for (int i = 0; i < data.Length; i++)
{
data[i] = UnityEngine.Random.Range(0.0f, 1.0f);
}
}
```

Audio samples mute optimization

---

Plugin~/WebRTCPlugin/Codec/CMakeLists.txt
Plugin~/WebRTCPlugin/Codec/CreateVideoCodecFactory.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.h
Plugin~/WebRTCPlugin/Codec/SimulcastEncoderFactory.cpp
Plugin~/WebRTCPlugin/Codec/SimulcastEncoderFactory.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Samples~/Menu/Menu.unity
Samples~/Scripts/SceneSelectUI.cs
Samples~/Simulcast.meta
Samples~/Simulcast/Simulcast.unity
Samples~/Simulcast/Simulcast.unity.meta
Samples~/Simulcast/SimulcastSample.cs
Samples~/Simulcast/SimulcastSample.cs.meta
WebRTC~/ProjectSettings/EditorBuildSettings.asset

This PR fixes this issue. #925
This PR adds simulcast support for NvCodec and a new sample scene to test the feature. This change refer to the original implementation by @aet is here. #956
Added sample scene to test this feature.

feat: simulcast H264 NvCodec

---

Runtime/Scripts/VideoStreamTrack.cs

fix: Video sender flips texture vertically by default

---

Plugin~/README.md

It looks like there should an unzip step that's missing. Also there's a typo in the folder name being set to the environment variable.

doc: Update README.md

---

Runtime/Scripts/RTCDataChannel.cs

This PR is for RTCDataChannelInit class and RTCDataChannel. I under stand the rule one class for one PR though, These two classes are written in one files. I integrated the PRs into one.

Dw24 rtc data channel

---

README.md

readme: update Unity badges
