Unity-Technologies/com.unity.webrtc

Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Runtime/Scripts/Context.cs

Occur crash when called `WebRTC.Finalize()` with peer connection established.
Calling delayed delegate when peer connection closed
Dispose delegates before peer connection closed as  ignore unintended delegate calling.

fix: Dispose delegates before peer connection closed

---

.editorconfig
.yamato/upm-ci-webrtc-packages.yml
Plugin~/WebRTCPlugin/Callback.cpp
Plugin~/WebRTCPlugin/Codec/EncoderFactory.cpp
Plugin~/WebRTCPlugin/Codec/EncoderFactory.h
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.mm
Plugin~/WebRTCPlugin/NvVideoCapturer.cpp
Plugin~/WebRTCPlugin/NvVideoCapturer.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPluginTest/ContextTest.cpp
Plugin~/WebRTCPluginTest/NvCodec/NvEncoderTest.cpp
Plugin~/WebRTCPluginTest/VideoCapturerTest.cpp
Runtime/Scripts/Context.cs
Runtime/Scripts/MediaStream.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/ContextTest.cs
Tests/Runtime/DataChannelTest.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/NativeAPITest.cs
Tests/Runtime/PeerConnectionTest.cs
Tests/Runtime/WaitUntilWithTimeout.cs
Tests/Runtime/WaitUntilWithTimeout.cs.meta

- Added `WebRTC.Initialize()` method argument `encoderType`
- Added tests for Software/Hardware encoder using parameterized tests methods
- ~~Mac OS unit tests on Yamato are failed~~
- ~~Test com.unity.webrtc with mono 2019.3 on macos~~
- ~~Test com.unity.webrtc with il2cpp 2019.3 on macos~~

refactor: select encoder

---

Runtime/Scripts/MediaStream.cs
Runtime/Scripts/WebRTC.cs

This PR is changing the way of capturing the audio buffer.
It uses the method `OnAudioFilterRead` instead of `AudioRenderer` class.
`public static void Update()`
`public static void Update(float[] audioData, int channels)`

fix: Changing Audio API

---

Tests/Runtime/PeerConnectionTest.cs

warning CS0219: The variable 'channel2' is assigned but its value is never used

fix: Fixing CS0219 warning 

---

.yamato/promotion.yml
.yamato/upm-ci-publish-github-release.yml
Plugin~/WebRTCPlugin/Codec/EncoderFactory.cpp
Plugin~/WebRTCPlugin/Codec/EncoderFactory.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.h
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/Cuda/CudaContext.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp
Plugin~/WebRTCPlugin/NvVideoCapturer.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.vcxproj
Runtime/Scripts/WebRTC.cs
Samples~/MediaStreamSample.cs
Tests/Runtime/DataChannelTest.cs
Tests/Runtime/InitializeOnLoad.cs
Tests/Runtime/InitializeOnLoad.cs.meta
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/NativeAPITest.cs

- added delay load dlls (`nvcuda.dll`, `vulkan-1.dll`)
- added native API `NativeMethods.GetHardwareEncoderSupport`
- changed attribute to exclude tests for hardware encoder when tests run on the poor pc

fix: delay load dlls for vulkan

---

CHANGELOG.md
WebRTC~/Packages/com.unity.webrtc/package.json
package.json

This PR is for the hotfix of [this issue](https://github.com/Unity-Technologies/UnityRenderStreaming/issues/227).
This problem caused by the misunderstanding about the CI process.
According to the process of the CI tool called Yamato, `promote` command only works copying the artifact made from `publish command`.
But `publish` command does not overwrite the package when already uploaded the same version. And unfortunately, this job succeeds even if the package is not uploaded. 
- will depend `promote` job on `publish` job
- will fix the build process to return failure when the package is not uploaded

chore: Upgrade package to fix dll error 

---

Plugin~/WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.cpp
Plugin~/WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.h
Plugin~/WebRTCPluginTest/ContextTest.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTest.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.h
Plugin~/WebRTCPluginTest/NvCodec/NvEncoderTest.cpp
Plugin~/WebRTCPluginTest/VideoCapturerTest.cpp
Plugin~/WebRTCPluginTest/WebRTCPluginTest.vcxproj

This PR contains the parameterized test using `ValuesIn` in googletest ([link](https://github.com/google/googletest/blob/572e261b607585d7044ad3321f9530d5c14a2564/googletest/docs/advanced.md#how-to-write-value-parameterized-tests)).
This achieves combination test for Rendering API(`D3D11`, `D3D12`, `OpenGL`, `Metal`, `Vulkan`) and encoder type (`hardware`, `software`).
Have not completed yet to implement `D3D12` native test because it is difficult to make a mock of `IUserInterface`.

refactor: Added Parameterized Test with ValuesIn

---

BuildScripts~/build_plugin.sh
CHANGELOG.md
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderCuda.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderD3D11.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderGL.cpp
WebRTC~/Packages/com.unity.webrtc/package.json
package.json

This is for a **hotfix version 1.1.2** for `com.unity.webrtc` package
- OpenGL color order error (Issue of Unity Render Streaming [#239](https://github.com/Unity-Technologies/UnityRenderStreaming/issues/239))

fixed: Color bug using OpenGL Encoder

---

Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/IntPtrExtension.cs
Runtime/Scripts/IntPtrExtension.cs.meta
Runtime/Scripts/MediaStream.cs
Runtime/Scripts/MediaStreamTrack.cs
Runtime/Scripts/RTCDataChannel.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/NativeAPITest.cs

- Add utility method `ConvertString`
- Changed `PeerConnectionObject::GetConfiguration()` method return value
- Add IntPtr extension method to free native memory

refactor: Changed the way of pass native string 

---

Plugin~/WebRTCPlugin/Codec/IEncoder.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.h
Plugin~/WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.h
Plugin~/WebRTCPlugin/Codec/VideoToolbox/VTEncoderMetal.h
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/DummyVideoEncoder.cpp
Plugin~/WebRTCPlugin/DummyVideoEncoder.h
Plugin~/WebRTCPlugin/Logger.cpp
Plugin~/WebRTCPlugin/NvVideoCapturer.cpp
Plugin~/WebRTCPlugin/NvVideoCapturer.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/UnityVideoEncoderFactory.cpp
Plugin~/WebRTCPlugin/UnityVideoEncoderFactory.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.vcxproj
Plugin~/WebRTCPlugin/WebRTCPlugin.vcxproj.filters
Plugin~/WebRTCPlugin/pch.h
Plugin~/WebRTCPluginTest/ContextTest.cpp
Plugin~/WebRTCPluginTest/WebRTCPluginTest.vcxproj
Plugin~/WebRTCPluginTest/WebRTCPluginTest.vcxproj.filters
Runtime/Scripts/Context.cs
Runtime/Scripts/MediaStream.cs
Runtime/Scripts/MediaStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/ContextTest.cs
Tests/Runtime/InitializeOnLoad.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/NativeAPITest.cs

In this PR fixed bitrate issue
- `DummyVideoEncoder` receives events from webrtc API to control bitrate
- Define `IVideoEncoderObserver` class to detect events on `DummyVideoEncoder`
- `Context` class implements `IVideoEncoderObserver` and process the callback
- Remove `bitrate` parameter from MediaStreamTrack API because the feature not supported yet
First, the original design has problems that the hardware encoder has been placed out of `DummyVideoEncoder`. It should be refactored but will take some time, so I don't fix it in this version.
`UnityVideoEncoderFactory` that factory class to make video encoders but in this current version only can support h264. It should be supported others like VP8, Vp9, and AV1.

fix: bitrate control

---

.yamato/meta/environments.yml
.yamato/promotion.yml
.yamato/upm-ci-webrtc-packages.yml
Tests/Runtime/MediaStreamTest.cs

This fix is for updating the yaml of Yamato because the upm registry URL is changed.

chore: Update yaml to replace upm registry

---

Plugin~/WebRTCPluginTest/WebRTCPluginTest.vcxproj

if version up (CUDA / Vulkan), failed build

chore: use macro on webrtc plugin test library path

---

Runtime/Scripts/Context.cs
Runtime/Scripts/WebRTC.cs

This PR adds a workaround to avoid the crash when executing auto-refresh on Unity Editor.
This crash is caused by not executing dispose of resources when hot reload. So need to add the event when reloading assembly.

fix: workaround to avoid the crash on Unity editor

---

Plugin~/WebRTCPlugin/WebRTCPlugin.vcxproj
Plugin~/WebRTCPluginTest/WebRTCPluginTest.vcxproj

Symbols in `jsoncpp.lib` the static link library already moved into `webrtc.lib`.
Visual Studio project should be changed CMake files.

chore: remove link library from visual studio project

---

Plugin~/WebRTCPlugin/Context.cpp
Runtime/Scripts/RTCPeerConnection.cs
Tests/Runtime/DataChannelTest.cs

This PR related the issue the user reported. https://github.com/Unity-Technologies/com.unity.webrtc/issues/97
The cause of the crash is the default parameters of the  `RTCDataChannelInit`.
Fixed the native code to return `nullptr` when the argument is incorrect.
And fixed the managed code to throw the exception when returned the null from the native-side.

fix: fixed DataChannel crash bug

---

Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.h
Plugin~/WebRTCPluginTest/ContextTest.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTest.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.h
Plugin~/WebRTCPluginTest/NvCodec/NvEncoderTest.cpp
Plugin~/WebRTCPluginTest/VideoCapturerTest.cpp

This PR is for fixing the memory leak issue #123 reported by a user on the Unity Forum.
This [line](https://github.com/Unity-Technologies/com.unity.webrtc/pull/123/files#diff-9b61b8ef15be0cd78f836c22b23ffd33R117) is needed to make the GPU command list.
```c++
ThrowIfFailed(m_commandAllocator->Reset());
```
To fix this issue, fixed the following point.
- Add native test of DX12
- Check HRESULT with `ThrowIfFailed` method
I referenced [this site]() to know how to use DX12 API.

fix: Memory leak when using RTX sample

---

Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Runtime/Scripts/MediaStreamTrack.cs

Occurring a crash when disposing a video track.
The `GraphicsDevice` instance must be single one in a runtime. The instance is shared by video tracks, but it was
removed with removing the video track.

fix: Fixed a crash bug when dispose a video track

---

Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/unity/include/IUnityEventQueue.h
Plugin~/unity/include/IUnityGraphicsMetal.h
Plugin~/unity/include/IUnityProfiler.h
Plugin~/unity/include/IUnityProfilerCallbacks.h
Plugin~/unity/include/IUnityRenderingExtensions.h
Plugin~/unity/include/IUnityShaderCompilerAccess.h
Plugin~/unity/include/LICENSE.md

This is experimental feature. 
It works only Unity 2020, not work 2019.4LTS.
This changes can shows the duration of encoding process on timeline in the profiler window.

feat: Show the item of encoding process into timeline in profiler window

---

.npmignore
Runtime/Scripts/IntPtrExtension.cs
Runtime/Scripts/RTCPeerConnection.cs

This PR is for adding a scripting reference of `RTCPeerConnection`.
XML format based on [DocFX](https://dotnet.github.io/docfx/).
This change is only one part of a huge number of APIs. 
We are going to add docs of APIs step-by-step from now on.
Unfortunately, DocFX doesn't support `include` tag so we need to write example code into C# code.

doc: scripting reference of RTCPeerConnection

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/NativeAPITest.cs

There were some failures in unit test of standalone build on Linux.
The timing of fail is when dispose operation of `Context`.
The operation on render thread is keeping after `Context` is disposed, so checking existence a context is needed. 
Moreover, it needed the lock during deleting the `Context` because operations on the render thread may access the context.
**NativeAPITest.CallVideoEncoderMethods** is failed on Windows so it is needed to fix.

fix: Fix linux standalone error

---

Runtime/Scripts/WebRTC.cs
Tests/Runtime/MediaStreamTest.cs

Related issue https://github.com/Unity-Technologies/com.unity.webrtc/issues/126.
Two unittests is added. (but one of two is excluded from auto test in current version)
This test is for checking the operation of disposing video track after instantiate it.
Sadly, this occurs a crash with current version, so it is added an `Ignore` attribute.
In next version it will be fixed.
This test is for checking the operation of instantiating and disposing multiple video tracks.

test: Add unittest which check the operation of multiple video tracks

---

Plugin~/WebRTCPlugin/Codec/IEncoder.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.h
Plugin~/WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.h
Plugin~/WebRTCPlugin/Codec/VideoToolbox/VTEncoderMetal.h
Plugin~/WebRTCPlugin/Codec/VideoToolbox/VTEncoderMetal.mm
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/DummyVideoEncoder.cpp
Plugin~/WebRTCPlugin/DummyVideoEncoder.h

Related issue https://github.com/Unity-Technologies/com.unity.webrtc/issues/100 .
This issue is the feature of recovering video quality do not work well after low bandwidth.
More detail of the issue is in the thread (#100).
The argument of `VideoEncoder::SetRates` has a `framerate_fps` parameter which is a value estimating frame rate.
This parameter is very high compared real interval of each encoding process. So NvEnc outputs the encoded data that data size smaller than expected. The estimation of bandwidth keeps low unless the encoder sends the proper sized data.
To fix this issue, need the individual way of estimating frame rate. `webrtc::RateStatistics` class was used for the implementation.
The present implementation of the encoder is messy. In the next version 2.2, we will refine …

fix: Video stream remains with bad quality after a short network degradation

---

Runtime/Scripts/Context.cs
Runtime/Scripts/WebRTC.cs

Forum issue: https://forum.unity.com/threads/unity-render-streaming-introduction-faq.742481/page-9#post-6172726
The EntryPoint has already been removed from the library.
Now that we are supporting multi-track, we need to check initialization each track.

fix: delete entry point about codec initialization result

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Plugin~/WebRTCPlugin/DataChannelObject.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/RTCDataChannel.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/DataChannelTest.cs
Tests/Runtime/SignalingPeers.cs

Related issue #167 .
`RTCDataChannel.Send` method must be called when `RTCDataChannel.ReadyState` is **Open**, but this state had not checked until now.
For fixing the issue, the new property `RTCDataChannel.ReadyState` is implemented and published.

fix: Add RTCDataChannel API to fix the behaviour of the "Send" method

---

BuildScripts~/build_libwebrtc_macos.sh
BuildScripts~/patches/add_objc_mac.patch
Plugin~/WebRTCPlugin/CMakeLists.txt
Plugin~/WebRTCPluginTest/CMakeLists.txt
Plugin~/cmake/FindFramework.cmake
Plugin~/cmake/FindWebRTC.cmake

VideoToolbox is a implementation of encoder/decoder optimized for Mac/iOS.
The library libwebrtc has the code for supporting VT but it is not linked in default.
To use this, need to contain objective-c code into libwebrtc.
- Add a patch file to link objective-c code.
- Define `WEBRTC OBJC INCLUDE DIR` in FindWebRTC.cmake.
- Add AVFoundation framework which used by objc code.

chore: Add objc modules to libwebrtc for mac

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.h
Plugin~/WebRTCPlugin/DummyVideoEncoder.cpp
Plugin~/WebRTCPlugin/DummyVideoEncoder.h

Related issues. #182  , #183 and also check this PR https://github.com/Unity-Technologies/UnityRenderStreaming/pull/331
This PR is for reverting changes [previous one](https://github.com/Unity-Technologies/com.unity.webrtc/pull/162).
In changes #162 , fixed the issue that the bandwidth is not returned to its original value from low bandwidth.
In reality, this problem has occurred by the custom SDP. 
Using customized SDP has risk because libwebrtc 's implementation might be changed.

fix: Revert changes of SetRates method

---

Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.h
Plugin~/WebRTCPlugin/SetSessionDescriptionObserver.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.h
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/NativeAPITest.cs
Tests/Runtime/PeerConnectionTest.cs

Changed to use primitive elements instead of RTCError.
I was going to take it as Struct, but it didn't work out...

chore: fix rtcerror message handling

---

Plugin~/WebRTCPlugin/DummyVideoEncoder.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/RTPParameters.cs
Tests/Runtime/NativeAPITest.cs
Tests/Runtime/PeerConnectionTest.cs

Related issue #191 .
This pull request adds a parameter `minBitrate` to `RTCRtpEncodingParameters` class to control a bitrate of video streaming more freely by user.
`RTCRtpEncodingParameters` class has already a parameter `maxBitrate` to control the bitrate, but this affects to the actual bitrate gradually. In contrast, `minBitrate` parameter affects the bitrate immediatelly.

feat: add "minBitrate" parameter to RTCRtpEncodingParameters class

---

BuildScripts~/build_plugin.cmd
Plugin~/WebRTCPlugin/Codec/EncoderFactory.cpp
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/UnityVideoTrackSource.cpp
Plugin~/WebRTCPlugin/UnityVideoTrackSource.h
Plugin~/WebRTCPluginTest/CMakeLists.txt
Plugin~/WebRTCPluginTest/NvCodec/NvEncoderTest.cpp

This pull request fixes bugs occurred when using debug build plugin.
- Add command to build `googletest` for debug
- Manage a list of references of `MediaStreamTrackInterface` to check the track whether disposed or not
- Add a mutex to `UnityVideoTrackSource` to avoid access from render thread after dispose it

fix: fixed crash when using debug build plugin

---

Plugin~/WebRTCPlugin/UnityRenderEvent.cpp

When doing some testing on the native plugin I had closed the profiler and started getting null pointer exceptions.

Add a nullptr check for profiler in development build

---

Samples~/DataChannelSample.cs
Samples~/PeerConnectionSample.cs
Samples~/StatsSample.cs

I am not sure why this was happened, but the class name `RTCIceCandidate` had ZWSP character.

fix: Remove ZWSP

---

Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPlugin/pch.h
Runtime/Scripts/Context.cs
Runtime/Scripts/RTCErrorException.cs
Runtime/Scripts/RTCErrorException.cs.meta
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/PeerConnectionTest.cs

This pull request Changes behavior of methods `SetRemoteDescription` and `SetLocalDescription`.
These methods occurred crashes when passed an invalid parameter. For this changes, methods handle the invalid parameter properly.
```csharp
var peer = new RTCPeerConnection();
RTCSessionDescription empty = new RTCSessionDescription();
Assert.Throws<ArgumentException>(() => peer.SetLocalDescription(ref empty));
RTCSessionDescription invalid = new RTCSessionDescription { sdp = "this is invalid parameter" };
Assert.Throws<RTCErrorException>(() => peer.SetLocalDescription(ref invalid));
```
```csharp
var peer = new RTCPeerConnection();
RTCSessionDescription empty = new RTCSessionDescription();
Assert.Throws<ArgumentException>(() => peer.SetRemoteDescription(ref empty));
RTCSessionDescription …
```

feat: Throw an exception when occurred error while setting a session description to a connection

---

Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/MediaStreamTrack.cs
Runtime/Scripts/RTCRtpReceiver.cs
Runtime/Scripts/RTCRtpSender.cs
Runtime/Scripts/RTCRtpTransceiver.cs
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Samples~/VideoReceiveSample.cs
Tests/Runtime/PeerConnectionTest.cs
Tests/Runtime/VideoReceiveTest.cs

- add test about `AddTransceiver` that specify only track kind on peerconnection
- change `TransceiverGetTrack` to `ReceiverGetTrack`, this is to match https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver

test: add test about addtransceiver

---

Plugin~/WebRTCPlugin/Codec/EncoderFactory.cpp
Plugin~/WebRTCPlugin/Codec/IEncoder.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.h
Plugin~/WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.cpp
Plugin~/WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.h
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.mm
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalTexture2D.mm
Plugin~/WebRTCPlugin/UnityVideoEncoderFactory.cpp
Plugin~/WebRTCPlugin/UnityVideoEncoderFactory.h
Plugin~/WebRTCPlugin/UnityVideoTrackSource.cpp
Plugin~/WebRTCPlugin/UnityVideoTrackSource.h
Plugin~/WebRTCPluginTest/NvCodec/NvEncoderTest.cpp
Plugin~/WebRTCPluginTest/VideoTrackSourceTest.cpp

This pull request is changes to provide a hardware encoder using [VideoToolbox](https://developer.apple.com/documentation/videotoolbox) on MacOS.
VideoToolbox is supported almost Mac devices.
You can use it if you set a value `EncoderType.Hardware` to `WebRTC.Initialize` method. 
In this case, the video codec is as H.264 codec.

feat: Hardware encoder on macos support

---

Samples~/MultiVideoReceiveSample.cs

This PR merged a week ago changes arguments of `InitializeReceiver` method. Because of this, this script error occurred.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/218

fix: Fix script error in MultiVideoReceiveSample 

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/ScopedProfiler.cpp
Plugin~/WebRTCPlugin/ScopedProfiler.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp

`IUnityProfiler` class is very useful to profile CPU load of the specific operations. 
But we have to write tedious code like this.
```cpp
if (s_IsDevelopmentBuild && s_UnityProfiler != nullptr)
s_UnityProfiler->BeginSample(marker);
//
// write code 
//
if (s_IsDevelopmentBuild && s_UnityProfiler != nullptr)
s_UnityProfiler->EndSample(marker);
```
Also this code has risk which no call `EndSample`.
`ScopedProfiler` class imitates `std::lock_guard` class which releases a resource when call destructor.
```cpp
{
ScopedProfiler profiler(*marker);
//
// write code 
//
}
```

refactor: Add ScopedProfiler class to make simple to use profiler

---

Tests/Runtime/MediaStreamTrackTest.cs

In the past `VideoStreamTrackDisposeImmediately` testcase was excluded auto testing on CI because this test is failed.
This crash bug was fixed by this [PR](https://github.com/Unity-Technologies/com.unity.webrtc/commit/8e99a948282830595433a588a984286b035a012d#diff-44bed945d85b997eb21e41cd693009135b379f1036b1dd1595db2b12809f74ed) so I add this testcase.

test: Remove "Ignore" attribute from a testcase

---

Editor/PeerListView.cs
Editor/WebRTCStats.cs
Plugin~/WebRTCPlugin/Codec/EncoderFactory.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Runtime/Scripts/Context.cs
Runtime/Scripts/MediaStream.cs
Runtime/Scripts/MediaStreamTrack.cs
Runtime/Scripts/RTCDataChannel.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/RTCStats.cs
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WeakReferenceTable.cs
Runtime/Scripts/WeakReferenceTable.cs.meta
Runtime/Scripts/WebRTC.cs
Tests/Runtime/PeerConnectionTest.cs

Add fix to this PR.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/225
The cause of issue is that instances of the reference table are not removed even if dispose the instance.
In this PR, move the method call of `WebRTC.Table.Remove` into Dispose method.

fix: crash when hangup open webrtcstatuswindow

---

Plugin~/WebRTCPlugin/Codec/EncoderFactory.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.h
Runtime/Scripts/Context.cs
Runtime/Scripts/WebRTC.cs

Related issue.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/199
This issue occurred in the specific environment which not installed NVIDIA driver like Parallel Desktop.
To avoid invalid situations, throw an exception from `WebRTC.Initialize`.

fix: Check hardware encoder support when initialize

---

Editor/PeerStatsView.cs
Editor/WebRTCStats.cs
Runtime/Scripts/RTCStats.cs
Samples~/StatsSample.cs

This PR changes type of `RTCStats` dictionary key to `string` instead of composite key.
For this change, developers can use `RTCStatsReport.Get` method to get `RTCStats` value.
You can see added API below:
```csharp
RTCStats stats = report.Get(statsId);
```
or
```csharp
if(report.TryGetValue(statsId, out RTCStats stats))
{
...
}
```

refactor: Change type of RTCStats dictionary key in RTCStatsReport class

---

Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Samples~/Bandwidth/BandwidthSample.cs
Tests/Runtime/VideoReceiveTest.cs
WebRTC~/ProjectSettings/ProjectSettings.asset

- Fix the performance issue of `ConvertRGBToI420` method
- Edit ProjectSettings.asset of the project under WebRTC~ directory to change `Color Space` parameter to `Gamma` to `Linear`
- Change a texture format of the RenderTexture which using for the receiver with Vulkan API

fix: video streaming receiver is not worked with vulkan API

---

.yamato/upm-ci-webrtc-packages.yml

Frequently we have gotten the error on CI job for macos that missing a command under the python3 directory.
This PR fixes the error.

chore: fix yaml to fix CI error for macos

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderCuda.cpp
Plugin~/WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.cpp
Plugin~/WebRTCPlugin/Codec/SoftwareCodec/SoftwareEncoder.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanTexture2D.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.h

This PR fixes the crash bug that occurs during terminate the application using vulkan API.
It might be the cause of crash is the `vkDestroyDevice` function called from the plugin side. This logical device is allocated from Unity side.

fix: Fix crash bug when using vulkan API when the application ended

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp

Changed the order of operations for disposing instances. 
Encoder instances depend on the graphics device instance, so this crash occurs.

fix: fix crash bug on Vulkan API

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/GraphicsDevice/GraphicsUtility.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/GraphicsUtility.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/UnityVulkanInitCallback.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/UnityVideoTrackSource.cpp
Plugin~/WebRTCPlugin/UnityVideoTrackSource.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPluginTest/ContextTest.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.cpp
Plugin~/WebRTCPluginTest/VideoRendererTest.cpp
Plugin~/WebRTCPluginTest/VideoTrackSourceTest.cpp
Runtime/Scripts/Context.cs
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/ContextTest.cs
Tests/Runtime/NativeAPITest.cs

The cause of the crash is the way of calling Unity Native API.
`AccessTexture` method of `IUnityVulkan` class returns `nullptr` when called on the main thread, not the render thread.
I changed the place of the method call to `UnityRenderEvent` class which is called on just the render thread.

fix: fixed crash when occurs on standalone build with Vulkan API  

---

Plugin~/WebRTCPlugin/UnityVideoDecoderFactory.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/RTCRtpSender.cs
Runtime/Scripts/RTCRtpTransceiver.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/PeerConnectionTest.cs

- enable videotoolbox decoder on mac
- add transceiver direction handling api
- add transceiver direction test
- add replace track method on sender

feat: videotoolbox decoder and handle transceiver direction

---

.yamato/upm-ci-webrtc-packages.yml

This change adds the graphics API to test automatically on the CI.
- Vulkan on Windows
- Vulkan on Linux
- DirectX12 on Windows
All tests are passed for this change.
However, there are some issues in which auto testing is failed on the PC with an integrated GPU. We should fix them in near future.

chore: add gfx_types parameter to CI script

---

BuildScripts~/build_libwebrtc_ios.sh
BuildScripts~/build_libwebrtc_macos.sh
BuildScripts~/patches/add_objc_deps.patch

This PR provides a script to build `libwebrtc` for iOS.
- To create a universal framework, use `lipo` command
- `arm64` and `x86_64` are supported for iOS device and simulator
- Enable bitcode
```
webrtc
├── LICENSE.md
├── include
└── lib
├── libwebrtc.a
└── libwebrtcd.a
```

chore: build libwebrtc for iOS

---

BuildScripts~/build_plugin_linux.sh
BuildScripts~/build_plugin_mac.sh
BuildScripts~/build_plugin_win.cmd
Plugin~/README.md

These changes simplified scripts that build native plugins.
The step of installing `googletest` is not needed in the build script, so removed them.

refactor: Simplify scripts that build native plugins 

---

Runtime/Scripts/MediaStream.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/RTCStats.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/MediaStreamTrackTest.cs
Tests/Runtime/NativeAPITest.cs
Tests/Runtime/PeerConnectionTest.cs
Tests/Runtime/VideoReceiveTest.cs

This fix is for the crash that occurred when testing the standalone build with IL2CPP on macOS.
This issue is not reproduced with mono backend instead of IL2CPP.
It should treat `size_t` type in c++ code on 64bit architecture as `ulong` type in managed code, but had treated as `uint`.

fix: change value type "uint" to "ulong"

---

Runtime/Scripts/VideoStreamTrack.cs
Tests/Runtime/MediaStreamTrackTest.cs

Related issue https://github.com/Unity-Technologies/UnityRenderStreaming/issues/360 .
Up until now the constructor of `VideoStreamTrack` class accepts parameters unconditionally but now it checks the `GraphicsFormat` which is supported by the library.
If the format is invalid, the constructor throws `ArgumentException`.

fix: VideoStreamTrack constructor throws an exception if the arguments are invalid

---

Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPlugin/pch.h
Runtime/Scripts/RTCIceCandidate.cs
Runtime/Scripts/RTCIceCandidate.cs.meta
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs
Samples~/Bandwidth/BandwidthSample.cs
Samples~/ChangeCodecs/ChangeCodecsSample.cs
Samples~/DataChannel/DataChannelSample.cs
Samples~/MediaStream/MediaStreamSample.cs
Samples~/MultiVideoReceive/MultiVideoReceiveSample.cs
Samples~/MultiplePeerConnections/MultiplePeerConnectionsSample.cs
Samples~/MungeSDP/MungeSDPSample.cs
Samples~/PeerConnection/PeerConnectionSample.cs
Samples~/Stats/StatsSample.cs
Samples~/VideoReceive/VideoReceiveSample.cs
Tests/Runtime/DataChannelTest.cs
Tests/Runtime/IceCandidateTest.cs
Tests/Runtime/IceCandidateTest.cs.meta
Tests/Runtime/NativeAPITest.cs
Tests/Runtime/PeerConnectionTest.cs
Tests/Runtime/SignalingPeers.cs
Tests/Runtime/VideoReceiveTest.cs

Related issue : #274 
- Changed type of `RTCIceCandidate` from `struct` to `class`
- Added properties to `RTCIceCandidate` class based on [WebIDL](https://www.w3.org/TR/webrtc/#rtcicecandidate-interface)
```csharp
public class RTCIceCandidate : IDisposable
{
public string Candidate;
public string SdpMid;
public int? SdpMLineIndex;
public string Foundation;
public RTCIceComponent? Component;
public uint Priority;
public string Address;
public RTCIceProtocol? Protocol;
public ushort? Port;
public RTCIceCandidateType? Type;
public RTCIceTcpCandidateType? TcpType;
public string RelatedAddress;
public ushort? RelatedPort;
public string UserNameFragment;
}
```

feat: Add icecandidate properties

---

Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/RTCIceCandidate.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/IceCandidateTest.cs

This pull request fixes the issue reported on the forum.
https://forum.unity.com/threads/unity-render-streaming-introduction-faq.742481/page-11#post-6697456
`RTCIceCandidate.Candidate` property has been returned an invalid string until this fix.

fix: Fixed the bug of the ice candidate property

---

.yamato/upm-ci-webrtc-packages.yml
BuildScripts~/test_plugin_ios.sh
BuildScripts~/test_plugin_linux.sh
BuildScripts~/test_plugin_mac.sh
BuildScripts~/test_plugin_win.cmd
Plugin~/WebRTCPluginTest/CMakeLists.txt
Plugin~/WebRTCPluginTest/ContextTest.cpp

[FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) module enables to install a third-party content in CMake. It makes it easier to set up modules like `googletest`.

test: Use FetchContent to install googletest 

---

BuildScripts~/test_plugin_linux.sh
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderCuda.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderCuda.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderD3D11.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderD3D11.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderD3D12.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderD3D12.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderGL.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderGL.h
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPluginTest/CMakeLists.txt
Plugin~/WebRTCPluginTest/ContextTest.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.h
Plugin~/WebRTCPluginTest/Sanitizer.cpp
Plugin~/WebRTCPluginTest/pch.h
Plugin~/tools/lsan/lsan_suppressions.txt

This pull request adds [AddressSanitizer](https://clang.llvm.org/docs/AddressSanitizer.html) to detect memory issues in native tests.
Currently, AddressSanitizer works on only Linux. 
Visual Studio 2019 supports it experimentally, but it is not production-ready ([link](https://devblogs.microsoft.com/cppblog/asan-for-windows-x64-and-debug-build-support/)). 
Xcode(AppleClang) supports AddressSanitizer already, but LeakSanitizer is not supported yet.
If you want to debug the native code with a sanitizer on Clion, [this page](https://www.jetbrains.com/help/clion/google-sanitizers.html) is comfortable.
You need to set the parameters below to the environment variables before testing with AddressSanitizer.
NVIDIA libraries give a false positive so we need to list them on `suppressions.txt`. 
``` …
```

test: Add LeakSanitizer on linux

---

Runtime/Scripts/AudioStreamTrack.cs
Runtime/Scripts/MediaStream.cs
Tests/Runtime/MediaStreamTest.cs

In the past, the code below throws the exception because of the failure to cast the value to `AudioStreamTrack`.
```
var audioStream = Audio.CaptureStream();
var audioTrack = audioStream.GetTracks().First() as AudioStreamTrack;
```
This pull request fixes it to not throw the unexpected exception.

fix: Downcast of MediaStreamTrack is failed 

---

Runtime/Scripts/Context.cs
Runtime/Scripts/MediaStream.cs
Runtime/Scripts/MediaStreamTrack.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/RTCRtpSender.cs
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.AsyncOperation.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/MediaStreamTrackTest.cs
Tests/Runtime/PeerConnectionTest.cs

In the past, the disposable object like `RTCPeerConnection` crashes when access properties after disposed of it.
Example
```csharp
var connection = new RTCPeerConnection();
connection.Dispose();
Debug.Log(connection.ConnectionState); // crash!!!
```
This behavior is uncomfortable for developers and it becomes difficult to resolve the bug.
This change fixes it in order to throw an exception when access properties after instances are disposed of.

fix: Fixed crash bug when access instance after disposed of it

---

Runtime/Scripts/Context.cs
Runtime/Scripts/RTCRtpReceiver.cs
Runtime/Scripts/RTCRtpSender.cs
Runtime/Scripts/RTCRtpTransceiver.cs
Tests/Runtime/PeerConnectionTest.cs

The comparing result of `RTCRtpSender` is weird like this.
```csharp
var peer = new RTCPeerConnection();
var track = new AudioStreamTrack("audio");
var sender = peer.AddTrack(track);
var transceiver = peer.GetTransceivers().First();
Debug.Log(sender == transceiver.Sender);           // false
```
Two instances of `RTCRtpSender` are the same but the result is false.
The reason is creating a new instance when calling the `RTCRtpTransceiver.Sender` property.

fix: The comparing result of RTCRtpSender is wrong

---

CHANGELOG.md
Documentation~/install.md
Plugin~/CMakeLists.txt
README.md
WebRTC~/Packages/manifest.json
WebRTC~/Packages/packages-lock.json
WebRTC~/ProjectSettings/ProjectVersion.txt
package.json

- Update README
- Add changes of the version `2.3.2` to CHANGELOG
- Upgrade Unity editor version `2019.4.19.f1`

chore: Update CHANGELOG to release a bug fix version

---

.yamato/upm-ci-webrtc-packages.yml
BuildScripts~/build_libwebrtc_android.sh
BuildScripts~/build_libwebrtc_ios.sh
BuildScripts~/build_libwebrtc_linux.sh
BuildScripts~/build_libwebrtc_macos.sh
BuildScripts~/build_plugin_ios.sh
BuildScripts~/build_plugin_linux.sh
BuildScripts~/build_plugin_mac.sh
BuildScripts~/test_package_mac.sh
BuildScripts~/test_plugin_ios.sh
BuildScripts~/test_plugin_linux.sh
BuildScripts~/test_plugin_mac.sh

- Changed the bokken image version to build a native plugin on linux
- Added `-eu` option to exit immediately if a command exits with a non-zero status.

chore: Fixed build error of native plugin on Linux

---

Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/PeerConnectionTest.cs

`RTCPeerConnection.OnConnectionStateChange` event notifies when changed state of `RTCPeerConnectionState`.
Should rebase on this PR https://github.com/Unity-Technologies/com.unity.webrtc/pull/319

feat: Add OnConnectionStateChange event on RTCPeerConnection

---

Runtime/Scripts/RTCPeerConnection.cs
Tests/Runtime/PeerConnectionTest.cs

This fix avoids key duplication error when calling `RTCPeerConnection.AddTrack`
```
ArgumentException: Item has already been added. Key in dictionary: '140720295394096'  Key being added: '140720295394096'
System.Collections.Hashtable.Insert (System.Object key, System.Object nvalue, System.Boolean add) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Collections.Hashtable.Add (System.Object key, System.Object value) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Unity.WebRTC.WeakReferenceTable.Add (System.Object key, System.Object value) (at Library/PackageCache/com.unity.webrtc@2.3.2-preview/Runtime/Scripts/WeakReferenceTable.cs:20)
Unity.WebRTC.RTCRtpSender..ctor (System.IntPtr ptr, Unity.WebRTC.RTCPeerConnection peer) (at Library/PackageCache/com.unity.webrtc@2.3.2-preview/Runtime/Scripts/RTC …
```

fix: Fixed key duplication error when calling `RTCPeerConnection.AddTrack`

---

Plugin~/WebRTCPlugin/Codec/EncoderFactory.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/IGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanTexture2D.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanTexture2D.h
Plugin~/WebRTCPlugin/PlatformBase.h
Plugin~/WebRTCPlugin/UnityVideoEncoderFactory.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.cpp
Tests/Runtime/ConditionalIgnore.cs
Tests/Runtime/NativeAPITest.cs

Fixed that `EncoderFactory::GetHardwareEncoderSupport()` method always returned `false` on Android platform.

fix: Enable hardware codec on Android platform 

---

Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/UnityVideoRenderer.cpp

`GL_BGRA_EXT` is not supported by some Android devices. 
`GraphicsUtility::ConvertRGBToI420Buffer` method does not support **RGBA** color format, so this fix is changing the operation for converting RGB to I420 on Android.

fix: Fix bugs of opengl API on android

---

Editor/BuildProcessor.cs

**Apple silicon** is not supported by WebRTC package right now.
This pull request is to notify that users using unsupported architecture.
We will get started Apple silicon support in near future.

feat: Check architecture of the build target on osx

---

Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.h
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs
Samples~/Bandwidth/BandwidthSample.cs
Samples~/ChangeCodecs/ChangeCodecsSample.cs
Samples~/DataChannel/DataChannelSample.cs
Samples~/MediaStream/MediaStream.unity
Samples~/MediaStream/MediaStreamSample.cs
Samples~/Menu/Menu.unity
Samples~/MultiVideoReceive/MultiVideoReceiveSample.cs
Samples~/MultiplePeerConnections/MultiplePeerConnectionsSample.cs
Samples~/MungeSDP/MungeSDPSample.cs
Samples~/PeerConnection/PeerConnectionSample.cs
Samples~/Stats/StatsSample.cs
Samples~/TrickleIce/TrickleIceSample.cs
Samples~/VideoReceive/VideoReceiveSample.cs
Tests/Runtime/DataChannelTest.cs
Tests/Runtime/PeerConnectionTest.cs
Tests/Runtime/SignalingPeers.cs
Tests/Runtime/VideoReceiveTest.cs

from `peer_connection_interface.h`
```
// These options are left as backwards compatibility for clients who need
// "Plan B" semantics. Clients who have switched to "Unified Plan" semantics
// should use the RtpTransceiver API (AddTransceiver) instead.
//
// offer_to_receive_X set to 1 will cause a media description to be
// generated in the offer, even if no tracks of that type have been added.
// Values greater than 1 are treated the same.
//
// If set to 0, the generated directional attribute will not include the
// "recv" direction (meaning it will be "sendonly" or "inactive".
```
So, I use Direction property on Transceiver for changing `Send / Recv` .

chore: remove offer to receive video/audio options

---

Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/MediaStreamTrackTest.cs

add validate method `ValidateGraphicsFormat` and check graphics format on video stream track constructor.

chore: validate graphics format on video stream track constructor

---

Editor/BuildProcessor.cs

webrtc package supported only x64 architecture on windows.
Issue: https://github.com/Unity-Technologies/com.unity.webrtc/issues/307
`BuildTarget.StandaloneWindows` is windows 32bit buildtarget.
`BuildTarget.StandaloneWindows64` is windows 64bit buildtarget.

chore: check windows architecture in build process

---

README.md

The fix is for the request in this comment.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/15#issuecomment-823716424

doc: Remove note for limitation which is for old version

---

Editor/BuildProcessor.cs
WebRTC~/ProjectSettings/ProjectSettings-android-vulkan.asset
WebRTC~/ProjectSettings/ProjectSettings.asset

When `Internet Access` in Build Settings for Android is set `Auto`, WebRTC apps don't work.
This change fixes the build process to output a warning log when `Internet Access` is not set `Required`.

chore: internet permission for Android

---

Samples~/TrickleIce/TrickleIceSample.cs

Changing arguments of the `CreateOffer` method that affected the behaviour of the `TrickleIce` sample.
The process of gathering ICE candidate has not occurred after calling `SetLocalDescription` caused by previous changes.

fix: Fix TrickleIce sample

---

.yamato/upm-ci-libwebrtc.yml
.yamato/upm-ci-webrtc-packages.yml
BuildScripts~/build_plugin_ios.sh
BuildScripts~/template/remote.sh.template
BuildScripts~/test_package_mac.sh

This pull request updates the macos image to upgrade XCode version 12.2.
Since XCode 12.2, we can build and test for Apple Silicon. Apple Silicon will be supported near future.

chore: Upgrade XCode version 12.2 for CI

---

Runtime/Scripts/WebRTC.cs
Tests/Runtime/ConditionalIgnore.cs
Tests/Runtime/NativeAPITest.cs
Tests/Runtime/VideoReceiveTest.cs

Since Unity2020 `CommandBuffer.IssuePluginCustomTextureUpdateV2` API is supported on DX12, so changed the condition in the the `VideoDecoderMethods` class.

fix: Video decoder support on DirectX12

---

Samples~/Scripts/BackButton.cs
Samples~/Scripts/SceneSelectUI.cs

Remove unused APIs from Scripting API of the package documents.

fix: Change public to internal to fix scripting API docs

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/pch.h
Samples~/ChangeCodecs/ChangeCodecs.unity
Tests/Runtime/TransceiverTest.cs

In the past, the hardware decoder is always used even if disabling hardware acceleration.
Because of this problem, users had not able to select decoders other than the default on several platforms.

fix: Use the software video decoder when disabling hardware acceleration  

---

.yamato/upm-ci-webrtc-packages.yml

- Changed ADB keys.
- Remove auto testing for iOS platform temporarily

chore: Fix setting for the Android auto testing on Yamato CI

---

Plugin~/README.md

This PR relates to this issue: https://github.com/Unity-Technologies/com.unity.webrtc/issues/434
A Windows developer's first time build will fail if they have older versions of Windows SDK installed. However the C++ compiler is incredibly vague, and debugging the issue can take days to figure out. I have added a warning to `README.md` to prevent this.

Help Windows devs save major debugging time with first time builds

---

Runtime/Scripts/AudioStreamTrack.cs
Runtime/Scripts/VideoStreamTrack.cs
Samples~/VideoReceive/VideoReceiveSample.cs
Tests/Runtime/ContextTest.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/MediaStreamTrackTest.cs
Tests/Runtime/PeerConnectionTest.cs

- remove label argument
- use `Guid` instead of label 
- add `EqualId` test
related: https://github.com/Unity-Technologies/UnityRenderStreaming/issues/464

chore: remove label argument from MediaStream/MediaStreamTrack

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Runtime/Scripts/Internal/Marshalling.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/PeerConnectionTest.cs

The issue has been occured since this [PR](https://github.com/Unity-Technologies/com.unity.webrtc/pull/419).
The new parameter should be optional, but this was defined as a required parameter. This pull request redefines parameters in `RTCConfiguration` as optional values.

fix: Fixed the issue that CreateDataChannel method returns null

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/UnityVideoDecoderFactory.cpp
Plugin~/WebRTCPlugin/UnityVideoDecoderFactory.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/Context.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/NativeAPITest.cs
Tests/Runtime/PeerConnectionTest.cs
Tests/Runtime/SignalingPeers.cs

This is a workaround to generate SDPs contains H.264 codec for unit testing.
The previous method is unstable because it is premised on the fixed contents of SDPs.
The workaround will be removed if CUDA HW decoder is supported.

fix: Workaround for testing with H.264 codec

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/UnityVideoRenderer.cpp
Plugin~/WebRTCPlugin/UnityVideoRenderer.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/MediaStream.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Samples~/VideoReceive/VideoReceive.unity
Samples~/VideoReceive/VideoReceiveSample.cs
Tests/Runtime/ConditionalIgnore.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/VideoReceiveTest.cs

The cause of the crash is that the texture data used by `UnityRenderingExtEventUpdateTexture` is null.
Changed `UnityVideoRenderer` to shared_ptr and add reference in `UnityRenderEvent`.

fix: crash windows vulkan on VideoReceieSample

---

Plugin~/README.md

Solves issue https://github.com/Unity-Technologies/com.unity.webrtc/issues/441.
Issue https://github.com/Unity-Technologies/com.unity.webrtc/issues/441 shows that on some Windows environments, building will fail at the linking stage when running `build_plugin_win.cmd`, probably due to having multiple C++ compilers on the user's computer.
This PR adds a message in README.md in similar vein to PR https://github.com/Unity-Technologies/com.unity.webrtc/pull/438 that gives a solution/workaround for Windows devs encountering linker issues.
I'm not really sure this is the best solution to the problem, ideally a change to the CMake that would make it link the correct standard library version would be best. But as a temporary thing, this works, and is [actually a valid use of CMake as described in …

doc: Save Windows devs first time build debug time (issue #441)

---

Plugin~/README.md

Fixes issue https://github.com/Unity-Technologies/com.unity.webrtc/issues/444.
I might just be an idiot but it's quite easy for noob developers to miss an absolutely **critical** step in native plugin dev process, which is that "Load on startup" needs to be ticked.
As demonstrated in issue https://github.com/Unity-Technologies/com.unity.webrtc/issues/444, the crash logs are incredibly obscure (as C++ is in general) and do not point at the right issue. Although the solution is already in the README, it's non-obvious and put as a subheading under an unrelated section. This makes it decently likely people miss this step, especially as the phrase "Deploying" generally refers to what developers do _after_ their code is working and ready for staging/prod, which may not register in their mind …

doc: Reduce the chance noob devs will miss critical (crash-preventing) build info

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Runtime/Scripts/RTCStats.cs
Tests/Runtime/PeerConnectionTest.cs
Tests/Runtime/VideoReceiveTest.cs

Fix
- Remove duplicate registration
- Fix VideoSource Stats property types
- Add check OnRemoveTrack invoke test
ToDo about VideoReceiveTest
- Investigating longer execution time
- Sometimes happen Unhandled error message about NullRef on PcOnRemoveTrack

Fix: crash when onremovetrack is invoked at registered

---

Runtime/Scripts/AudioSourceRead.cs
Runtime/Scripts/AudioStreamTrack.cs
Runtime/Scripts/MediaStreamTrack.cs
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Samples~/Audio/AudioSpectrumView.cs
Tests/Runtime/AudioStreamTrackTest.cs
Tests/Runtime/MediaStreamTrackTest.cs
Tests/Runtime/NativeAPITest.cs

This PR published APIs for setting audio binary data to tracks directly. Developers can set audio data to `AudioStreamTrack` without an `AudioSource` instance.
Other fixes below:
- Refactor `MediaStreamTrack` class
- Use `ConcurrentDictionary` in `VideoStreamTrack` instead of `lock` object

refactor: Add AudioStreamTrack SetData API 

---

Runtime/Scripts/WebRTC.cs
Tests/Runtime/WebRTCTest.cs

- throw exception when call WebRTC.Initialize twice

fix: crash when call WebRTC.Initialize twice

---

Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/RTCRtpReceiver.cs
Runtime/Scripts/RTCRtpSender.cs
Samples~/VideoReceive/VideoReceiveSample.cs

By disposing the track, the rendering process of the received video is stopped.

fix: dispose receive track on OnRemoveTrack

---

Runtime/Scripts/AudioStreamTrack.cs
Runtime/Scripts/RTCPeerConnection.cs
Samples~/Audio/AudioSpectrumView.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/SignalingPeers.cs

`NativeArray<T>.ReadOnly` type is not supported on Unity2019, so I add an override method to fix it.

fix: Fix compile error on Unity2019

---

Runtime/Scripts/AudioStreamTrack.cs
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs

Fix the crash bug in the `PerfectNegotiation` sample scene.
```
[impolite-Peer] SRD Offer SignalingState Stable
0x00007FFC9C17538E (UnityPlayer) UnityMain
0x00007FFC9C179FC7 (UnityPlayer) UnityMain
0x00007FFC9C076883 (UnityPlayer) UnityMain
0x00007FFC9C074BD6 (UnityPlayer) UnityMain
0x00007FFC9C24E4D3 (UnityPlayer) UnityMain
0x00007FFC9C24E244 (UnityPlayer) UnityMain
0x00007FFC9C3C487C (UnityPlayer) UnityMain
0x00007FFC9C429D0C (UnityPlayer) UnityMain
0x000001CEE243ED10 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.Object:DestroyImmediate (UnityEngine.Object,bool)
0x000001CEE243EC53 (Mono JIT Code) UnityEngine.Object:DestroyImmediate (UnityEngine.Object)
0x000001CEE243E143 (Mono JIT Code) Unity.WebRTC.VideoStreamTrack:Dispose ()
0x000001CEE243DF89 (Mono JIT Code) …
```

fix: Call the method UnityEngine.Object.DestroyImmediate on main thread

---

Runtime/Scripts/AudioSourceRead.cs
Runtime/Scripts/AudioStreamTrack.cs
Samples~/Audio/AudioSample.cs

This pull request fixes the issue that it is different pitches of audios between peers on iOS platform.
In detail, The change is using `AudioClip.GetData` instead of `MonoBehaviour.OnAudioFilterRead` to get the audio buffer from `AudioClip`.

fix:  Change procedures of getting audio binary array

---

Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/RTCRtpTransceiver.cs
Runtime/Scripts/WebRTC.cs
Samples~/VideoReceive/VideoReceiveSample.cs
Tests/Runtime/AudioStreamTrackTest.cs
Tests/Runtime/DataChannelTest.cs
Tests/Runtime/IceCandidateTest.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/MediaStreamTrackTest.cs
Tests/Runtime/PeerConnectionTest.cs
Tests/Runtime/SignalingPeers.cs
Tests/Runtime/TransceiverTest.cs
Tests/Runtime/VideoReceiveTest.cs
Tests/Runtime/WebRTCTest.cs

This change is for fixing the resource leak in the **VideoReceiver** sample.
Need to call `RTCRtpTransceiver.Stop` method explicitly to dispose of the encoder.

fix: Resource leak in VideoReceiver sample

---

Samples~/VideoReceive/VideoReceiveSample.cs

If press immediately HangUp button after press Call button, occur null reference exception.

fix: Occur Null Reference when press HangUp on VideoReceiveSample

---

CHANGELOG.md
Runtime/Scripts/Internal/ExecutableUnitySynchronizationContext.cs
Runtime/Scripts/Internal/ExecutableUnitySynchronizationContext.cs.meta
Runtime/Scripts/WebRTC.cs

**Problem**: WebRTC does not provide control over when messages are received and the message callbacks are processed due to the active `SynchronizationContext`.
**Example Use-Case**:
- Users wish to control when WebRTC polls for messages.  Users want RTCDataChannels to be checked for messages during Update, and OnBeforeRender to poll for input data to process logic and then poll for more recent input data before rendering.
**Solution**:
Add a custom `SynchronizationContext` that has an internal method `ExecutePendingTasks` allowing WebRTC to process messages that have been queued up for processing by the native code.  Then add a public method to the `WebRTC` class to allow users to manually process events from the main thread.

XR Feature Request: Executable Task Processing with WebRTC

---

Plugin~/NvCodec/NvCodec/NvDecoder/NvDecoder.cpp
Plugin~/NvCodec/NvCodec/NvEncoder/NvEncoderCuda.cpp
Plugin~/NvCodec/NvCodec/NvEncoder/NvEncoderCuda.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
README.md
Third Party Notices.md

There are small typos in:
- Plugin~/NvCodec/NvCodec/NvDecoder/NvDecoder.cpp
- Plugin~/NvCodec/NvCodec/NvEncoder/NvEncoderCuda.cpp
- Plugin~/NvCodec/NvCodec/NvEncoder/NvEncoderCuda.h
- Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
- Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
- README.md
- Third Party Notices.md
Fixes:
- Should read `separate` rather than `seperate`.
- Should read `support` rather than `suppport`.
- Should read `routines` rather than `rouines`.
- Should read `failed` rather than `faild`.
- Should read `explicitly` rather than `explicitely`.
- Should read `error` rather than `erorr`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

Plugin~/WebRTCPlugin/UnityAudioTrackSource.cpp
Plugin~/WebRTCPlugin/UnityAudioTrackSource.h

Hello.
I found current implementations as below are not working due to missing member initialize.
https://github.com/Unity-Technologies/com.unity.webrtc/blob/8bf0f084ec8c58b69b29f0c7e50f41243f835796/Plugin~/WebRTCPlugin/Context.cpp#L396-L400
In order to fix it without modifying libwebrtc, I added the `cricket::AudioOptions` member and `options()` overrided function to `LocalAudioSource` itself to enable accessing `_options` member correctly.

Fix audio options not working correctly

---

Plugin~/WebRTCPlugin/UnityAudioTrackSource.cpp
Runtime/Scripts/AudioStreamTrack.cs
Tests/Runtime/AudioStreamTrackTest.cs

`AudioStreamTrack.SetData` method had bugs that it occurs crashes when pass invalid arguments like zero or null.

fix: Fix a bug of AudioStreamTrack.SetData method

---

CHANGELOG.md
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/Internal/ExecutableUnitySynchronizationContext.cs
Runtime/Scripts/RTCDataChannel.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/DataChannelTest.cs
Tests/Runtime/Unity.WebRTC.RuntimeTests.asmdef

This adds support to the `RTCDataChannel` for sending the basic Native Collections `NativeArray<T>`, `NativeSlice<T>` and `NativeArray<T>.ReadOnly`.
- Adds `Send` functionality to `RTCDataChannel` for each native collection described above.
- Adds `Send` functionality to `RTCDataChannel` for arbitrary pointers in the `unsafe` context and `IntPtr`s.
- Adds Native Collection send test cases where applicable.
Currently is in a first pass and not completely ready for review but tests are passing.

Add Support for Sending Basic Native Collections

---

Tests/Runtime/TransceiverTest.cs

This is a workaround for the failure of testcase `TransceiverTest.TransceiverStop`.
Disposing process of MediaStreamTrack is unstable when using GC.
At the moment, Dispose methods needs to be called on the main thread for workaround.

test: Workaround for failure of testcase TransceiverTest.TransceiverStop 

---

Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/DummyAudioDevice.cpp
Plugin~/WebRTCPlugin/DummyAudioDevice.h
Plugin~/WebRTCPlugin/UnityAudioTrackSource.cpp
Plugin~/WebRTCPlugin/UnityAudioTrackSource.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/AudioSourceRead.cs
Runtime/Scripts/AudioStreamTrack.cs
Runtime/Scripts/Context.cs
Runtime/Scripts/WebRTC.cs

Hello.
As commented in #525, current audio playback is often unstable and has very high latency.
In order to reduce latency and improve playback quality, I tried to change to work `AudioClip` of `AudioStreamRenderer` as streaming mode  and reduce sample length of `AudioClip`.
I think it works better than current implementation, has lower latency and less frequently glitch.
Thank you in advance for your review.

Improve audio playback stability using streaming AudioClip

---

Runtime/Scripts/Context.cs
Runtime/Scripts/WebRTC.cs
Samples~/MediaStream/MediaStreamSample.cs
Tests/Runtime/ConditionalIgnore.cs
Tests/Runtime/TestHelper.cs

related issue: https://github.com/Unity-Technologies/com.unity.webrtc/issues/528

Fix: avoid crash using OpenGLCore on windows

---

.yamato/upm-ci-webrtc-packages.yml
BuildScripts~/template/remote.sh.template

This pull request adds auto-testing jobs for supporting macOS architectures below.
editor version | target device name | runtime architecture
-- | -- | --
2019.4 | macos | x64
2019.4 | macos-m1 | x64 (rosetta 2)
2020.3 | macos | x64
2020.3 | macos-m1 | x64 (rosetta 2)
2021.2 | macos | x64
2021.2 | macos-m1 | x64 (rosetta 2)
2021.2 | macos-m1 | arm64

chore: Auto testing for macOS Apple Silicon 

---

Plugin~/unity/include/IUnityGraphics.h
Plugin~/unity/include/IUnityGraphicsD3D11.h
Plugin~/unity/include/IUnityGraphicsD3D12.h
Plugin~/unity/include/IUnityGraphicsVulkan.h
Plugin~/unity/include/IUnityLog.h
Plugin~/unity/include/IUnityProfiler.h
Plugin~/unity/include/IUnityRenderingExtensions.h
Plugin~/unity/include/IUnityShaderCompilerAccess.h

These header files are brought from the `PluginAPI` folder in Unity Editor 2021.2.6.
`C:\Program Files\Unity\Hub\Editor\2021.2.6f1\Editor\Data\PluginAPI`

feat: Update plugin interface headers provided by Unity2021.2.6

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoder.cpp

H264 profile Level `NV_ENC_LEVEL_H264_51` do not allow a framerate over 120.
So change maxFramerate.

fix: avoid crashes when using Full HD resolution with HWA enabled on Windows

---

Runtime/Scripts/AudioStreamTrack.cs
Samples~/Audio/AudioSample.cs
Samples~/MultiAudioReceive/MultiAudioReceiveSample.cs
Samples~/MultiplePeerConnections/MultiplePeerConnectionsSample.cs
Samples~/VideoReceive/VideoReceiveSample.cs
Tests/Runtime/AudioStreamTrackTest.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/MediaStreamTrackTest.cs
Tests/Runtime/PeerConnectionTest.cs

Hello.
As commented in #525, current audio playback has very high latency.
In order to resolve this, I tried to call `SetData()` of `AudioClip` with an offset which refers the sample position from attached `AudioSource`. It's a tricky way but works well.
Thank you in advance for your review.

Reduce audio latency using buffer position from attached AudioSource

---

Plugin~/WebRTCPlugin/Context.cpp
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/VideoReceiveTest.cs

`VideoStreamTrack` created a `UnityVideoRenderer ` instance internally even if the video track is the sender side. This change fixes the issue by not sharing the constructor for sender and receiver.

fix: Separate VideoStreamTrack constructor for video receiver and video source

---

Samples~/E2ELatency/E2ELatencySample.cs

`Application.targetFramerate` is ignored when not setting `Don't Sync` for `Application.vSyncCount`.
For details below.
https://docs.unity3d.com/ScriptReference/Application-targetFrameRate.html

fix: Change QualitySettings.vSyncCount parameter to change framerate

---

Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Runtime/Scripts/VideoStreamTrack.cs

This pull request fixed process of creating texture for receiving video.
There was a bug that not receiving video when using Vulkan API on Windows. This bug had been occurred since #517.
The reason is that color space conversion is failed because texture format was changed the previous changes.

fix: Fixed texture format for the video stream receiver

---

Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/AudioStreamTrack.cs
Runtime/Scripts/Context.cs
Runtime/Scripts/WebRTC.cs

This pull request adds `AudioStreamTrack` constructor to send audio stream.
In the past, `AudioStreamTrack` constructor is only one, which needs `AudioSource` instance.
To use with other components like AudioListener, we needed to add another constructor.

fix: Add AudioStreamTrack constructor for sending audio generated by AudioListener

---

Samples~/Bandwidth/Bandwidth.unity
Samples~/ChangeCodecs/ChangeCodecs.unity
Samples~/MediaStream/MediaStream.unity
Samples~/MultiAudioReceive/MultiAudioReceive.unity
Samples~/MultiVideoReceive/MultiVideoReceive.unity
Samples~/MultiplePeerConnections/MultiplePeerConnections.unity
Samples~/MungeSDP/MungeSDP.unity
Samples~/PeerConnection/PeerConnection.unity
Samples~/TrickleIce/TrickleIce.unity
Samples~/VideoReceive/VideoReceive.unity

There are `BoxCollider` components in sample scenes but these are not needed.
It can remove not wanted log below.

fix: Removed unused components in sample scenes

---

Runtime/Scripts/RTCRtpSender.cs
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Samples~/Audio/AudioSample.cs
Samples~/Bandwidth/BandwidthSample.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/WebRTCTest.cs

- Validate texture resolution after scaling down
- Add test `SetParametersReturnErrorIfInvalidTextureResolution` (only run Android)
- On `BandWidth` sample, if happen error, output failed text on statusField.

fix: avoid crash when set parameters (scaleResolutionDownBy)

---

Samples~/MediaStream/MediaStreamSample.cs

fix change: 0a80cd4
- `RemoveTrack` only call from Sender(pc1) side.
- Remove `OnNegotiationNeeded` process on Receiver(pc2) side
- Register `OnRemoveTrack` process for dispose track on Receiver(pc2) side

fix: failed SetRemoteDescription when call RemoveTrack on MediaStreamSample

---

BuildScripts~/build_plugin_ios.sh
Documentation~/index.md

In the past, when developers build iOS app with WebRTC library, they needed to take a troublesome step below. 
> To make the archive for **iOS platform** to publish App Store, you need to use `lipo` command to eliminate the `x86_64` architecture from the binary in the `webrtc.framework`.
>
> ```lipo -remove x86_64 Runtime/Plugins/iOS/webrtc.framework/webrtc -o Runtime/Plugins/iOS/webrtc.framework/webrtc``` 
>
The cause of this, the iOS framework contains binary for two architecture to support iOS and iOS simulator. But I guess that almost developers want to skip the step instead of not available to build for iOS simulator.
The fundamental solution is using XCFramework, but currently not supported by Unity Editor.
If you have any ideas, please share them.

chore: Remove iOS Simulator support

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/DummyAudioDevice.cpp
Plugin~/WebRTCPlugin/DummyAudioDevice.h
Samples~/Audio/AudioSample.cs

Related issue.
#525, #602
I investigated the issue of audio latency, and I found that there is a routine for processing audio buffer regularly, this doesn’t run at exact intervals.
I replaced this routine for periodic execution to [`RepeatingTaskHandle`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/rtc_base/task_utils/repeating_task.h).

fix: Replace routine of periodic execution for audio buffer to fix audio latency

---

Plugin~/WebRTCPlugin/AudioTrackSinkAdapter.cpp
Plugin~/WebRTCPlugin/UnityAudioTrackSource.cpp

The original PR is here. #613 @aet fixed this.
(cherry picked from commit eecce18f3589684ac533e0022dd587b94abfadd3)
This change is replacing the process of conversions between `int16_t` and `float`.
`webrtc::S16ToFloat` and `webrtc::FloatToS16` are provided by webrtc library.

fix: Audio conversion improvements

---

BuildScripts~/build_libwebrtc_android.sh
BuildScripts~/build_libwebrtc_ios.sh
BuildScripts~/build_libwebrtc_linux.sh
BuildScripts~/build_libwebrtc_macos.sh
Plugin~/WebRTCPlugin/AudioTrackSinkAdapter.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/AudioStreamTrack.cs
Runtime/Scripts/RTCStats.cs

The following code stopped triggering for me on PC once https://github.com/Unity-Technologies/com.unity.webrtc/pull/563 landed, while it still works on Mac/Linux where everything is built with Clang. I rarely use this functionality, so I didn't bother to debug this much further, but changing the type does help.
After changing the type, the plugin works the same if built with VS or Clang for PC
```
foreach (var rtpReceiver in pc.GetReceivers())
{
RTCStatsReportAsyncOperation op = rtpReceiver.GetStats();
yield return op;
if (!op.IsError)
{
foreach (RTCStats stats in op.Value.Stats.Values)
{
RTCStatsType type = stats.Type;
if (type == RTCStatsType.InboundRtp)
{
Debug.Log("RTCStatsType.InboundRtp")
}
if (type == RTCStatsType.Track)
{
Debug.Log("RTCStatsType.Track")
}
}
}
op.Value?.Dispose(); …
```

Fix RTCStats.Type regression on Windows

---

Runtime/Scripts/WebRTC.cs

This `return: MarshalAs` seems to be wrong, since it's not used for other functions with `RTCErrorType` return type.
Although it doesn't cause any error in Unity, I think it's still better to remove it, unless I have misunderstood something.

fix: remove wrong return marshal

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
Documentation~/install.md
README.md
package.json

#630 fixes a crash bug which occurrs high frequency. So we decided to release hotfix version for developers using it.

chore: Upgrade the package version 2.4.0-exp.6

---

Plugin~/WebRTCPlugin/Dynlink/libcuda.so.init.c
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/LoadVulkanFunctions.cpp
Plugin~/WebRTCPlugin/UnityVideoRenderer.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp

When I was updating Nvidia drivers on various Linux environments, I noticed that in some cases libvulkan.so and libcuda.so are simply missing and WebRTC crashes. But core unity renderer continues to get initialized as it's depending on libvulkan.so.1 instead on Linux and for some reason uses libvulkan.so explicitly for Android.
There's also a small error handling fix for current hardware encoder probe in case we have not detected a graphics device at all. Loading of vulkan driver fails, yet we shouldn't even get to this point as core unity has already moved forward using vulkan.

linux vulkan loader fix

---

Plugin~/CMakeLists.txt

This pull request picks the commit from #620 made by @aet
Changes the minimum version of deployment target for macos to 10.12.

chore: Properly set deployment target for mac/ios

---

Plugin~/NvCodec/CMakeLists.txt
Plugin~/WebRTCPlugin/CMakeLists.txt

Fixed cmake code to set enable fpic option of clang compiler for NvCodec library.

fix: Set enable fpic option for NvCodec library on Linux

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.cpp

- Use `SupportedNvDecoderCodecs` on `NvEncoderFactory::GetSupportedFormats()` for avoid throw invalid error on `SetCodecPreference`
- remove constrained profile from `SupportedNvDecoderCodecs`.  constrained profile not supported ( refer by document )

fix: SetCodecPreference throws invalid error

---

Plugin~/WebRTCPlugin/CMakeLists.txt

Added linker flag `delayload` to reduce dependencies on windows platform.
Two dll are removed from dependencies.
- nvEncodeAPI64.dll
- nvcivod.dll

fix: Add linker flag `delayload` to reduce dependencies on Windows

---

Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLContext.cpp

Fixed the crash bug caused by not returning the `EGLContext` which already created.

fix: Fix crach when using Android GLES3

---

.yamato/upm-ci-webrtc-packages.yml
Plugin~/WebRTCPlugin/GpuMemoryBuffer.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp
Plugin~/WebRTCPlugin/UnityVideoDecoderFactory.cpp
Plugin~/WebRTCPlugin/UnityVideoEncoderFactory.cpp
Plugin~/WebRTCPluginTest/CMakeLists.txt
Plugin~/WebRTCPluginTest/ContextTest.cpp
Plugin~/WebRTCPluginTest/GpuMemoryBufferPoolTest.cpp
Plugin~/WebRTCPluginTest/GpuMemoryBufferTest.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceContainer.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceContainerTest.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTest.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTestBase.h
Plugin~/WebRTCPluginTest/InternalCodecsTest.cpp
Plugin~/WebRTCPluginTest/NvCodec/CudaDeviceTest.cpp
Plugin~/WebRTCPluginTest/NvCodec/NvCodecTest.cpp
Plugin~/WebRTCPluginTest/NvCodec/NvDecoderImplTest.cpp
Plugin~/WebRTCPluginTest/NvCodec/NvEncoderImplTest.cpp
Plugin~/WebRTCPluginTest/UnityVideoDecoderFactoryTest.cpp
Plugin~/WebRTCPluginTest/UnityVideoEncoderFactoryTest.cpp
Plugin~/WebRTCPluginTest/VideoFrameTest.cpp
Plugin~/WebRTCPluginTest/VideoRendererTest.cpp
Plugin~/WebRTCPluginTest/VideoTrackSourceTest.cpp
Plugin~/WebRTCPluginTest/pch.h
Plugin~/tools/sanitizer/lsan_suppressions.txt

We are using google test for C/C++ testing and running tests automatically on CI. This pull request adds the type of instance for testing. The instances have no GPUs, so auto testing can check the features of fallback when nothing graphics device. 
Also, testcases are skipped when the testing environment don't meet the requirements.

fix: Add the testing platforms which GPU is not installed

---

Samples~/Bandwidth/Bandwidth.unity
Samples~/Bandwidth/BandwidthSample.cs

Added the dropdown list UI to select the framerate of encoding video.
We haven't support the encoding framerate adjustment yet. So, this option don't work unfortunately.

fix: Add framerate option in Bandwidth sample scene

---

.yamato/upm-ci-webrtc-packages.yml
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.cpp

This pull request update Linux image for testing native code.
This package doesn't require the CUDA runtime but it occurred crash when launching the app without CUDA library.

fix: Update the Linux image to test the native code without cuda runtime

---

Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.h

Created texture with RGBA format with OpenGLCore 
https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Runtime/Scripts/WebRTC.cs#L588
So, NV_ENC_BUFFER_FORMAT needs same same alignment.

fix: Fix using NV_ENC_BUFFER_FORMAT on OpenGLCore

---

BuildScripts~/build_plugin_linux.sh
BuildScripts~/test_plugin_linux.sh
Plugin~/.clang-format
Plugin~/WebRTCPlugin/CMakeLists.txt
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/UnityVulkanInitCallback.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanUtility.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanUtility.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/UnityVulkanInterfaceFunctions.h
Plugin~/WebRTCPluginTest/CMakeLists.txt
Plugin~/WebRTCPluginTest/GraphicsDeviceContainer.cpp

This pull request contains two main fixes below.
- Replace Vulkan instance initialization
- Replace **glut** to **glfw3**
Replace `IUnityGraphicsVulkan` to `IUnityGraphicsVulkanV2` as an interface of Unity and use `AddInterceptInitialization` instead of `InterceptInitialization`. This fix multiple packages can customize the initialization process of vulkan instance.
And the Vulkan initialization process contains loading Vulkan extensions for CUDA interoperability. Even if the process for CUDA is failed, it works without HWA codec features.
Replace **glut** to **glfw3** for c++ testing because glut library occurs crash issues on some Linux platform.

fix: Use IUnityGraphicsVulkanV2 to intercept Vulkan initialization process of Unity

---

Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.h

This bug is able to reproduced using `MultiVideoRecv` sample. This sample is for testing multi video tracks. The problem is displaying received video frames are wrong sometimes.
I fixed the bug by using `glFinish` function at the end of `OpenGL Graphics Device::CopyResource` method. I am checking whether there is another way because the function affects graphics performance.

fix: Fix the bug which the frame of receiving video is wrong when using OpenGL API

---

BuildScripts~/build_plugin_win.cmd
Plugin~/WebRTCPlugin/UnityVideoRenderer.cpp
Plugin~/WebRTCPlugin/VideoFrameAdapter.cpp
Plugin~/WebRTCPlugin/VideoFrameAdapter.h
Tests/Runtime/NativeAPITest.cs

This pull request fixes the crash occurring when using **MultiPeer** sample.
`VideoFrameAdapter::ConvertToVideoFrameBuffer` method changes the state of the `VideoFrameAdapter` instance. Moreover, multiple threads call this method at the same time.
So we need to protect the status with the synchronous object.

fix: Add lock object into the VideoFrameAdapter class

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp

Cache NvEnc Capability on `NvEncoderFactory`, it reduce calling `NvEncOpenSessionEx` api.
and implement TryCatch on initialize `NvEncoder` (include calling `NvEncOpenSessionEx`) for avoid crash when session limitation.

fix: crash perfectnegotiation using nvcodec

---

Plugin~/WebRTCPlugin/CMakeLists.txt
Plugin~/WebRTCPlugin/GpuMemoryBufferPool.cpp
Plugin~/WebRTCPlugin/GpuMemoryBufferPool.h
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLContext.cpp
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/X11.h
Plugin~/WebRTCPlugin/pch.h
Plugin~/WebRTCPluginTest/GpuMemoryBufferPoolTest.cpp

`GpuMemoryBufferPool` class manages lifetime of `Video Frame`, but there was a problem that remaining unused buffers in the buffer pool. This pull request fixes the issue by the timestamp when using the resource last time.

fix: Remove unused buffers in GpuMemoryBufferPool

---

Plugin~/WebRTCPluginTest/NvCodec/NvEncoderImplTest.cpp
Runtime/Scripts/WebRTC.cs
Tests/Runtime/WebRTCTest.cs

NvEncoder raises an exception if Width and Height are not supported by specified H264ProfileLevel.
However, the codec and its profile are determined when the encoder is initialized.
Therefore, when creating a VideoTrack, if the pixel count is uniformly 4k resolution or higher, `ValidateTextureSize` returns error.
- Add test about `NvEncoder` raises an exception if Width and Height are not supported by specified H264ProfileLevel.
- Add workaround on `ValidateTextureSize`
- Add more test about `ValidateTextureSize`

Fix: avoid crash invalid resolution on NvCodec

---

Plugin~/WebRTCPlugin/GpuMemoryBufferPool.cpp
Plugin~/WebRTCPlugin/GpuMemoryBufferPool.h
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/GpuMemoryBufferCudaHandle.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/GpuMemoryBufferCudaHandle.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp

- destructor process of `GpuMemoryBufferCudaHandle` need to called from RenderThread.
- `ReleaseStaleBuffers` called with `Encode` event on render thread

fix: release GpuMemoryHandle on RenderThread

---

Plugin~/CMakePresets.json
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.mm
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalTexture2D.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs

This pull request makes workaround for the issue that freezing the Unity editor on macOS Apple Silicon.
I already reported the bug to Unity team.
https://fogbugz.unity3d.com/default.asp?1419782_hputlaje02r19pbr

fix: Fix freeze bug when streaming video on macos Apple Silicon

---

Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.cpp

To copy the texture completely, `Flush` method should be called at the last of `CopyResource`.

fix: Fixed send frames in incorrect order on DX11

---

Plugin~/WebRTCPlugin/VideoFrameAdapter.cpp
Plugin~/WebRTCPlugin/VideoFrameAdapter.h
Plugin~/WebRTCPluginTest/GpuMemoryBufferTest.cpp

When using `scaleResolutionDownBy` parameter, the encoder calls the 'VideoFrameBuffer::GetI420()' to get I420 buffer, but `ScaledBuffer` is not provided the method, so it leads the crash.
Also the I420 buffer should be kept the instance in the `ScaledBuffer` instance, so the `scaledI40Buffers_` is added.

fix: Fix the crash bug when applying the scaleResolutionDownBy parameter in Bandwidth sample on macOS

---

Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalDevice.mm
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.mm

Fixed the issue below.
To copy the texture completely, `commit` method of `MTLCommandBuffer` should be called at the last.
https://user-images.githubusercontent.com/1132081/163503370-6873cde3-9354-4128-8543-382513dc729c.mov

fix: Fix issues of video streaming in multipeer sample on macOS

---

Runtime/Scripts/WebRTC.cs

This error was printed in the console log.
```
Destroy may not be called from edit mode! Use DestroyImmediate instead.
Destroying an object in edit mode destroys it permanently.
```
Checked `Application.isPlaying` and if it is false, use `Object.DestroyImmediate`.

fix: Fixed the error when stopping the playmode in Unity Editor

---

Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp

This issue occurred when releasing the PBO (Pixel Buffer Object) on Linux. The cause is calling `glBindBuffer` funtion before `glDeleteTextures`. No problem this line is removed.

fix: Fixed the crash when releasing the OpenGL resource on Linux

---

Runtime/Scripts/WebRTC.cs

Hello.
In order to work correctly APIs like `ScreenCapture.CaptureScreenshotIntoRenderTexture()` which depends on `WaitForEndOfFrame()`, preserving active render target before updating WebRTC video textures is added.
Thank you in advance for your review.

Add preserving active render target before updating WebRTC video textures

---

Samples~/Scripts/SceneSelectUI.cs

WebRTC supports video streaming for vertical layout so this pull request adds options to make convenience for testing.

fix: Add resolution option for vertical layout in menu scene

---

Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/UnityVulkanInitCallback.cpp

Hook_vkGetInstanceProcAddr should apply vkGetInstanceProcAddr and return the result by default. As it is now, subsequent plugins that are loaded by Unity will get the Hook_vkGetInstanceProcAddr from this package, which returns nullptr for all but the specific functions checked for.
The change in this pull request is not tested in any way, and not even compiled.

fix: Update UnityVulkanInitCallback.cpp

---

Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.h

fix commit 9d19591604b9c859878d78f89c479dae1d0353bf
- Changed to use the correct RowPitch.
- Changed to use libyuv convert.
resolve for https://github.com/Unity-Technologies/com.unity.webrtc/issues/520

fix: Fix invalid sendtexture on dx12 with Software encoder

---

Plugin~/WebRTCPlugin/UnityVideoTrackSource.cpp
Plugin~/WebRTCPlugin/UnityVideoTrackSource.h

Sometimes, at the timing of Dispose, the following line is thrown and a crash occurs in MacOS(Intel) building IL2CPP.
https://github.com/Unity-Technologies/com.unity.webrtc/blob/develop/Plugin~/WebRTCPlugin/UnityVideoTrackSource.cpp
error log
```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
```

fix: change shared_time_mutex to mutex

---

Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.mm

This pull request fixes the disruption of video frame when using multiple peers like Perfect Negotiation sample. This fix affects on iOS/macOS.
This video shows the issue.
https://user-images.githubusercontent.com/1132081/165681059-de0f0200-12f6-4584-b54f-c01abff5066e.mp4

fix: Received video images are weird when multiple peers stream video on macOS

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/MediaStreamObserver.cpp
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Runtime/Scripts/Context.cs
Runtime/Scripts/MediaStream.cs
Runtime/Scripts/MediaStreamTrack.cs
Runtime/Scripts/RTCPeerConnection.cs
Samples~/PeerConnection/PeerConnectionSample.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/SignalingPeers.cs

This pull request is for merging #644,
#644 is made by @aet, the fixes are right, but this leads the crash at another parts.
The crash is occurred when `MediaStream.OnRemoveTrack` is called from the native code. This method accesses `MediaStreamTrack` instance but this instance is already destroyed, so it leads the crash.

fix: Fix PeerConnection/MediaStreamObserver leaks and crash

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.h

#702, #695, #705
NvCodec supports Baseline, Main, High for H264 profile, but some browsers only supports **Constrained Baseline Profile** for H264 codec (ex: Firefox, Safari).
Constrained Baseline Profile is compatible with Baseline Profile, so NvCodec returns the profile to work fine with these browsers.

fix: Returns Constrained Baseline profile as an item of supported profile list from NvCodec

---

Plugin~/WebRTCPlugin/Codec/CMakeLists.txt
Plugin~/WebRTCPlugin/Codec/H264ProfileLevelId.cpp
Plugin~/WebRTCPlugin/Codec/H264ProfileLevelId.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.h
Plugin~/WebRTCPluginTest/CMakeLists.txt
Plugin~/WebRTCPluginTest/H264ProfileLevelIdTest.cpp
Plugin~/WebRTCPluginTest/NvCodec/NvEncoderImplTest.cpp

H.264 defines the maximum number of pixels and framerate depending on the profile level. The profile level used by most browsers is **3.1**, which does not support high-resolution frames such as Full HD. 
NvEnc will fail to initialize if an invalid profile level and resolution combination is specified. So as a workaround, it calculates a valid profile level for a given resolution and frame rate and uses it in NvEnc. Note that encoder initialization will fail if there is no valid profile level.
Currently, the framerate used by NvEnc is a fixed value of **30** because the encoder framerate depends on the Unity frame rate. This will be supported in the future.

fix: Fix error when using the video resolution which not supported by the H264 profile level

---

Editor/PeerStatsView.cs
Editor/WebRTCStats.cs
Runtime/Scripts/RTCStats.cs

- delete `estimatedPlayoutTimestamp` on OutboundStats
- add `RTCReceivedRtpStreamStats` and `RTCSenderRtpStreamStats` class
- start `GetStatsPolling` if already entered playing mode.
related ? https://github.com/Unity-Technologies/com.unity.webrtc/issues/706

fix: Fix RTCStats parameters for upgrading libwebrtc M92

---

Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.h

Related #717.
There was a issue that displaying video frame with flicker when using DX11 graphics API. The cause of the issue is the encoding process runs before ending copying process. Calling `Flush` method is not enough to fix the issue, it needed to wait finishing GPU process.

fix: Fix displaying video frame with out-of-order frames on DX11

---

.yamato/upm-ci-webrtc-packages.yml

The package test for releasing the package is failed because the CI image is not supported for the Vulkan graphics API.
This pull request makes workaround that replacing the graphics API to GLCore.

chore: Update Ubuntu20.04 image version for CI 

---

Plugin~/WebRTCPlugin/UnityVideoRenderer.cpp

This PR is https://github.com/Unity-Technologies/com.unity.webrtc/pull/707 rebased with current develop branch.
I check, test and review changeset.
Thanks for contributing @leejeonghun

fix: Fix crash could be occurred when using scaleResolutionDownBy parameter

---

TestRunnerOptions.json
Tests/Runtime/AudioStreamTrackTest.cs

**TestRunnerOptions.json** file is for internal use. Internal CI system refer to this to read settings for testing.
Usually Unity Test Framework can not test audio features because it runs Unity as batchmode. **disableBatchMode** flag works to test features which are not able to be tested on batchmode.

chore: Add TestRunnerOptions.json to set disable batchmode 

---

Plugin~/NvCodec/NvCodec/NvDecoder/NvDecoder.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvDecoderImpl.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvDecoderImpl.h
Plugin~/WebRTCPluginTest/NvCodec/NvCodecTest.cpp
Plugin~/WebRTCPluginTest/VideoCodecTest.cpp
Plugin~/WebRTCPluginTest/VideoCodecTest.h
Samples~/ReplaceTrack/ReplaceTrack.unity
Samples~/ReplaceTrack/ReplaceTrackSample.cs

Related issue https://github.com/Unity-Technologies/UnityRenderStreaming/issues/626
Fixed a crash during `ReplaceTrack` method. The cause of the crash was that the decoder was not accepting resolution changes.
The `NvDecoder` class calls the `NvDecoder::ReconfigureDecoder` method when it detects a resolution change in the `NvDecoder::Decode` method. However, the resolution change requires a prior call to the `NvDecoder::setReconfigParams` method, which must be called before the `NvDecoder::Decode` method is called. To detect a change in resolution, the resolution information is obtained from the SPS.

fix: Fix the crash when calling the ReplaceTrack method using NvCodec

---

Editor/PeerStatsView.cs
Tests/Runtime/AudioStreamTrackTest.cs

Editor scripts have referenced the deprecated parameters below.
- `RTCRTPStreamStats.mediaType`
- `RTCRTPStreamStats.trackId`

fix: Remove references to obsolute warning

---

Runtime/Scripts/RTCRtpReceiver.cs
Runtime/Scripts/WeakReferenceTable.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/AudioStreamTrackTest.cs

Related issue #631
This PR fixes the problem occurs by the gabage collection.
The instance of `WeakReference` class is destroyed when collected by GC, but the finalizer of the instance runs after destroying with slightly delay. If called `Dispose` method among the delay, it occurs the issue.

fix: Fixed the issue when garbage collected but the finalizer has not been called

---

Plugin~/WebRTCPlugin/CMakeLists.txt
Plugin~/WebRTCPlugin/Codec/NvCodec/NvDecoderImpl.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.h
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/GraphicsDevice/GraphicsUtility.h
Plugin~/WebRTCPlugin/ProfilerMarkerFactory.cpp
Plugin~/WebRTCPlugin/ProfilerMarkerFactory.h
Plugin~/WebRTCPlugin/ScopedProfiler.cpp
Plugin~/WebRTCPlugin/ScopedProfiler.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/UnityVideoDecoderFactory.cpp
Plugin~/WebRTCPlugin/UnityVideoDecoderFactory.h
Plugin~/WebRTCPlugin/UnityVideoEncoderFactory.cpp
Plugin~/WebRTCPlugin/UnityVideoEncoderFactory.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.h
Plugin~/WebRTCPluginTest/ContextTest.cpp
Plugin~/WebRTCPluginTest/UnityVideoDecoderFactoryTest.cpp
Plugin~/WebRTCPluginTest/UnityVideoEncoderFactoryTest.cpp
Plugin~/WebRTCPluginTest/VideoRendererTest.cpp
Plugin~/WebRTCPluginTest/VideoTrackSourceTest.cpp
Tests/Runtime/AudioStreamTrackTest.cs

Show the CPU duration of video encoder thread on Unity Profiler window.

feat: Profiling codec CPU performance on Unity Profiler window

---

.yamato/upm-ci-webrtc-packages.yml
Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.h
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/UnityVideoEncoderFactory.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceContainer.cpp
Plugin~/WebRTCPluginTest/NvCodec/NvCodecTest.cpp

Related issue #734.
This PR fixes the crash when launching Unity Editor on the machine which installing old NVIDIA driver.
If the CUDA version supported by the driver is lower than 11.0, NvCodec are removed from list of available codecs.

fix: Fix crash because of the old version of nvidia driver

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvDecoderImpl.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvDecoderImpl.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.h
Plugin~/WebRTCPlugin/GpuMemoryBuffer.cpp
Plugin~/WebRTCPlugin/GpuMemoryBuffer.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/IGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.mm
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/UnityVideoDecoderFactory.cpp
Plugin~/WebRTCPlugin/UnityVideoEncoderFactory.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceContainer.cpp
Plugin~/WebRTCPluginTest/NvCodec/NvCodecTest.cpp
Plugin~/WebRTCPluginTest/NvCodec/NvDecoderImplTest.cpp
Plugin~/WebRTCPluginTest/NvCodec/NvEncoderImplTest.cpp

Changed to be able to profile process in the detailed implementation of each graphics device class and Encoder / Decoder class.
example
1. NvEncoder.CopyResource
2. VulkanGraphicsDevice.CopyImage

feat: Display CPU loads of encoding/decoding thread more details

---

Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/GraphicsUtility.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/GraphicsUtility.h
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.mm
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp

Hello
In order to increase overall performance, this PR replaces remaining `GraphicsUtility::ConvertRGBToI420Buffer` with `libyuv::ARGBToI420`.
Thank you in advance for your review.

Use libyuv::ARGBToI420 instead of GraphicsUtility::ConvertRGBToI420Buffer

---

Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/Context.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/RTCRtpTransceiver.cs
Runtime/Scripts/RTPParameters.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/PeerConnectionTest.cs

This pull request adds the argument `RTCRtpTransceiverInit` to `RTCPeerConnection.AddTransceiver` method.
Developers can easily set bitrate or framerate for stream senders.
```csharp
RTCPeerConnection.AddTransceiver(MediaStreamTrack track, RTCRtpTransceiverInit init = null)
RTCPeerConnection.AddTransceiver(TrackKind kind, RTCRtpTransceiverInit init = null)
```

feat: Add the argument to RTCPeerConnection.AddTransceiver method to configure streaming

---

Plugin~/WebRTCPlugin/CMakeLists.txt
Plugin~/WebRTCPlugin/ProfilerMarkerFactory.cpp
Plugin~/WebRTCPlugin/ProfilerMarkerFactory.h
Plugin~/WebRTCPlugin/ScopedProfiler.cpp
Plugin~/WebRTCPlugin/ScopedProfiler.h
Plugin~/WebRTCPlugin/UnityProfilerInterfaceFunctions.cpp
Plugin~/WebRTCPlugin/UnityProfilerInterfaceFunctions.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/UnityVulkanInterfaceFunctions.cpp
Plugin~/WebRTCPlugin/UnityVulkanInterfaceFunctions.h

The native profiler registration thread is the same on macOS / iOS.
By using UnityProfilerV2, it will be registered as a different thread.

fix: Fix display probmen on CPU profiler for macOS/iOS platform

---

Plugin~/WebRTCPlugin/ProfilerMarkerFactory.cpp
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp

`UnityProfiler::Get` function returns `nullptr` when using Unity2019.4.

fix: Fix crash bug when using unity2019

---

Plugin~/WebRTCPlugin/Codec/CreateVideoCodecFactory.cpp

`RTCDefaultVideoEncoderFactory` class returns encoders which not implemented with VideoToolbox.

fix: Use RTCVideoDecoderFactoryH264 instead of RTCDefaultVideoEncoderFactory

---

Samples~/MediaStream/MediaStreamSample.cs
Tests/Runtime/MediaStreamTrackTest.cs
Tests/Runtime/PeerConnectionTest.cs

This pull request contains two fixes.
- Small fix MediaStream sample
- Add testcase for `RTCPeerConnection.AddTransceiver`

fix: Fix MediaStream sample and add managed test

---

Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanTexture2D.cpp
Plugin~/WebRTCPlugin/WebRTCMacros.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/RTCPeerConnection.cs

Fixed `RTCPeerConnection.AddTrack` method that stop to use generate GUID as a mediastream id when the argument of AddTrack is `null`.

fix: Fix RTCPeerConnection.AddTrack API

---

Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Runtime/Scripts/Context.cs
Runtime/Scripts/WebRTC.cs

This fix releases video frame buffers on the rendering thread in destructor of `Context` class.

fix: Release video frame buffers when destroying context instance

---

Plugin~/WebRTCPlugin/UnityVideoTrackSource.cpp
Plugin~/WebRTCPlugin/UnityVideoTrackSource.h
Plugin~/WebRTCPluginTest/ContextTest.cpp

`AdaptedVideoTrackSource::AdaptFrame` method skips encoding video frame when the video broadcaster not needed.

fix: Drop frame when the video broadcaster don't need the new frame

---

Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp

This PR fixes #779.
This fix the undefined behaviour of Vulkan API. 
We could not find this crash bug in QA because this worked correctly on several devices.
As a measure of this issue, we add Android devices for manual testing to cover several SoCs.
This issue is urgent so we are going to release the hotfix version ASAP.

fix: Fix crash on Android device pixel4a when using Vulkan

---

.yamato/upm-ci-webrtc-packages.yml

The stable version of upm-ci command is updated `1.28.0` with the changes that deprecated downloading unity-downloader-cli on the fly.
This fix adds the command line in the CI process that install unity-downloader-cli with pip.

chore: Fix issue caused by updating upm-ci-utils command

---

Plugin~/WebRTCPlugin/Codec/CreateVideoCodecFactory.h
Plugin~/WebRTCPluginTest/CMakeLists.txt
Plugin~/WebRTCPluginTest/CreateVideoCodecFactoryTest.cpp
Plugin~/WebRTCPluginTest/H264ProfileLevelIdTest.cpp

This pull request fixes the crash bug when streaming video between peers on macOS and Windows.
This crash occurs the difference of the "codec implementation" property in the `SdpVideoFormat` parameter.
`SdpVideoFormat`, the argument of `FindCodecFactory` function comes from another peer to negotiate available media codecs. The parameter "codec implementation" is used for determine codec, however, This determination process is wrong. It must be determined with the codec mimetype and profiles, not codec implementation.
We will release the hotfix version because this bug affects many users.

fix: Fix crash when streaming video between different platforms

---

Plugin~/README.md

I had to follow the setup instructions yesterday. Turns out the provided apt-key is out of date since [April 2022](https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/):
Old:
```
root@a9fc4909d8c5:/# apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
Executing: /tmp/apt-key-gpghome.MIERODK9ek/gpg.1.sh --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
gpg: requesting key from 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub'
gpg: key F60F4B3D7FA2AF80: public key "cudatools <cudatools@nvidia.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
root@a9fc4909d8c5:/# add-apt-repository "deb …
```

fix: [minor] Update public key in build environment setup

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/Context.cs
Runtime/Scripts/RTCStats.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/ContextTest.cs
Tests/Runtime/StatsReportTest.cs
Tests/Runtime/StatsReportTest.cs.meta

This fix relates #542 #799.
There were issues that creating/destroying RTCStatsReport instance in native code when it works with multi threading. This fix protects the shared resources using mutex, and added some test cases to check implementations of the RTCStatsReport.

fix: Fix the crash when passing the invalid argument to DeleteStatsReport method

---

Tests/Runtime/Attribute.cs
Tests/Runtime/Attribute.cs.meta
Tests/Runtime/ContextTest.cs
Tests/Runtime/IceCandidateTest.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/MediaStreamTrackTest.cs
Tests/Runtime/NativeAPITest.cs
Tests/Runtime/PeerConnectionTest.cs
Tests/Runtime/TransceiverTest.cs
Tests/Runtime/VideoReceiveTest.cs

This PR arranges test categories to exclude test cases taking long time to run.
Some test cases takes long time because they run asyncnously using coroutine, and also need many frames to find low reproducable issues. Many developers would abstain from running test case to avoid waiting long time.
Note: Unity Test Runner doesn't support filtering that can exclude test cases which developers specify categories. Therefore, we can set only one category per test cases.

test: Add test category to exclude test cases which take long time 

---

Plugin~/WebRTCPlugin/PeerConnectionStatsCollectorCallback.cpp
Plugin~/WebRTCPlugin/PeerConnectionStatsCollectorCallback.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/RTCStatsCollectorCallback.cs
Runtime/Scripts/RTCStatsCollectorCallback.cs.meta
Runtime/Scripts/WebRTC.AsyncOperation.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/PeerConnectionTest.cs

This PR fixes the issue that the coroutine which the return value of GetStats method, doesn't change the status when calling it multiple times at the same time.
Add `RTCStatsCollectorCallback` class which manages the native handle of the `GetStats` callback, and define the dictionary of `RTCStatsCollectorCallback` in RTCPeerConnection class.

fix: Fix bug when calling GetStats method multiple times at the same time

---

Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/RTCStatsCollectorCallback.cs
Runtime/Scripts/WebRTC.AsyncOperation.cs
Samples~/Stats/Stats.unity
Samples~/Stats/StatsSample.cs
WebRTC~/Packages/manifest.json
WebRTC~/Packages/packages-lock.json

The memory usage in Stats sample significantlly increased when updating statistics more frequently. This is a native memory resource of the `RTCStatsReport`. GC collection can't catch up the speed of inscreasing memory usage.
This PR fixes the issue by calling `Dispose` method explicitly to destroy the native resource.

fix: Fix memory leak in Stats Sample 

---

Runtime/Scripts/VideoStreamTrack.cs
Tests/Runtime/MediaStreamTest.cs

The property `RenderTexture.active` throws `UnityException` when accessing on the thread except of main thread.

fix: Fix UnityException when calling finalizer of VideoStreamTrack from GC

---

Tests/Runtime/DataChannelTest.cs
Tests/Runtime/PeerConnectionTest.cs
WebRTC~/Packages/packages-lock.json
WebRTC~/ProjectSettings/ProjectSettings.asset
WebRTC~/ProjectSettings/ProjectVersion.txt

Some iOS unit-tests works well on the local environment but they are failure on CI environments.
To avoid failures, this change excludes iOS platform for some unit-tests.

fix: Workaround of CI testing for iOS 

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/PeerConnectionObject.h
Plugin~/WebRTCPlugin/SetSessionDescriptionObserver.cpp
Plugin~/WebRTCPlugin/SetSessionDescriptionObserver.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.h
Runtime/Scripts/Context.cs
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/SetSessionDescriptionObserver.cs
Runtime/Scripts/SetSessionDescriptionObserver.cs.meta
Runtime/Scripts/WebRTC.AsyncOperation.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/ContextTest.cs
Tests/Runtime/NativeAPITest.cs
Tests/Runtime/PeerConnectionTest.cs

This pull request fixes the bug that the coroutine of `RTCPeerConnection.SetLocalDescription` and `RTCPeerConnection.SetRemoteDescription` doesn't complete sometimes.
This issue would be occurred when calling methods above multiple times at the same time.

fix: Fix RTCPeerConnection.SetLocalDescription callback

---

.yamato/verification.yml
Plugin~/WebRTCPlugin/GraphicsDevice/GraphicsDevice.cpp
Plugin~/WebRTCPlugin/PlatformBase.h
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/ConditionalIgnore.cs
Tests/Runtime/MediaStreamTest.cs
Tests/Runtime/MediaStreamTrackTest.cs
Tests/Runtime/NativeAPITest.cs
Tests/Runtime/PeerConnectionTest.cs
Tests/Runtime/TransceiverTest.cs
Tests/Runtime/VideoReceiveTest.cs
Tests/Runtime/WebRTCTest.cs

This pull request changes the behaviour of WebRTC initialization when using OpenGL on macOS or Windows.
After the change, `WebRTC.Initialize` method doesn't throw `NotSupportedException` even if you use OpenGL on all platforms. Alternatively, the constructor of `VideoStreamTrack` throws exception when using OpenGL graphics type on macOS and Windows.
It will makes availale to use the package for audio or data streaming with no supported graphics device.

fix: Exclude unit-tests for macOS plattform with OpenGL

---

Plugin~/WebRTCPlugin/CMakeLists.txt
Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/Context.h
Plugin~/WebRTCPlugin/CreateSessionDescriptionObserver.cpp
Plugin~/WebRTCPlugin/CreateSessionDescriptionObserver.h
Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/CreateSessionDescriptionObserver.cs
Runtime/Scripts/CreateSessionDescriptionObserver.cs.meta
Runtime/Scripts/RTCPeerConnection.cs
Runtime/Scripts/WebRTC.AsyncOperation.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/PeerConnectionTest.cs

Related issue #792.
This issues occurred when running process of `CreateOffer` / `CreateAnswer` methods of `RTCPeerConnection` class in parallel.

fix: Fix CreateOffer and CreateAnswer to execute in parallel

---

.yamato/verification.yml
Tests/Runtime/VideoReceiveTest.cs

This PR fixes testing for APV(A Package Verification).
- Fix verification test for iOS platform.
- Fix VideoReceiverTest that ignores test when the codec is not supported on the platform.

fix: Fix verification test for iOS platform

---

.yamato/upm-ci-webrtc-packages.yml
BuildScripts~/build_plugin_linux.sh
Documentation~/requirements.md
Plugin~/CMakeLists.txt
Plugin~/README.md
Plugin~/WebRTCPlugin/CMakeLists.txt

We have experienced the runtime error of lack of dependencies on Linux because the native plugin has depended on the C++ standard library as a dynamic linking. We need to install `libc++.so.1` and `libc++abi.so.1` into the Linux to fix the issue, but it is troublesome.
This pull request contains the fix of the CMake script to statically link the standard library.

fix: Remove libc++.so.1 dependency for Linux platform

---

.yamato/compile-package.yml
.yamato/upm-ci-webrtc-packages.yml
package.json

This relates the issue. https://github.com/Unity-Technologies/UnityRenderStreaming/pull/796
WebRTC package depends on Audio module which implicitly installed on Unity Editor. We need to list package dependencies on the `package.json` even if the one is installed modules.

fix: Add Audio module for dependency to solve the issue of isolation test and compilation test

---

BuildScripts~/build_plugin_linux.sh
BuildScripts~/test_plugin_linux.sh

The cause of the error is pip install commanad because of updating in third-party repository. It is [glad](https://github.com/Dav1dde/glad).
I found the changelog in the repository which can effect our build command.
https://github.com/Dav1dde/glad/commit/4a1168280e4c56e8d488f4de082a83bbc91c4fc4#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R28

fix: Fix build error libux plugin because of pip command error

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md
Documentation~/install.md
README.md
ValidationExceptions.json
package.json

We are preparing the package to promote pre-release version from experimental version because make the package to official. We need Package validation test for promoting the package, and the package validation test detected API breaking changes between previous package version 2.3.3-preview.
[APIValidation.txt](https://github.com/Unity-Technologies/com.unity.webrtc/files/9884693/APIValidation.txt)
To fix this, we need to update a major version, so this PR changes the package version to 3.0.0-pre.1.

chore: Update package version 3.0.0-pre.1 to fix package validation

---

BuildScripts~/build_libwebrtc_ios.sh
BuildScripts~/build_libwebrtc_macos.sh
BuildScripts~/patches/README.md
BuildScripts~/patches/disable_task_queue_gcd.patch

Task queuing in libwebrtc is implemented differently on each platform. 
macOS/iOS is implemented using [GCD (Global Central Dispatch)](https://developer.apple.com/documentation/DISPATCH). 
GCD makes no guarantees about which thread it uses to execute a task. Referenced [here](https://developer.apple.com/documentation/dispatch/dispatchqueue). 
Since UnityProfiler is implemented assuming execution in the same thread, it was changed to use TaskQueue implementation by STDLIB which is executed in the same thread.
No performance degradation when using STDLIB Task Queue.

fix: Use stdlib TaskQueue instead of GCD TaskQueue

---

.yamato/coverage.yml
Editor/PeerStatsView.cs
Runtime/Scripts/AudioStreamTrack.cs
Runtime/Scripts/Context.cs
Runtime/Scripts/Internal/IntPtrExtension.cs
Runtime/Scripts/RTCPeerConnection.cs
Tests/Runtime/AudioStreamTrackTest.cs
Tests/Runtime/ContextTest.cs
Tests/Runtime/DataChannelTest.cs
Tests/Runtime/IntPtrTest.cs
Tests/Runtime/PeerConnectionTest.cs
WebRTC~/Packages/manifest.json
WebRTC~/Packages/packages-lock.json

This pull request improves test coverage. 
I found the main reason of decreasing the coverage score is the issue of Code Coverage package.
The latest version 1.2.2 of Code Coverage package has issues which ignores the covering some code. So it decreased the coverage score. This issue is not reproduced with the previous version 1.1.1 so I downgraded the package.
I got the result below after improving.
- Line coverage: 83.5%
- Method coverage: 80.3%

test: Downgrade Code Coverage package 1.1.1 for increasing test coverage score

---

Documentation~/requirements.md

for Android
- Choose **Require** for **Internet Access** in Player Setting Window.
for iOS
- On the Xcode **Build Settings** tab, in the **Build Options** group, set Enable Bitcode to **No**.

doc: Update documentation for build settings for mobile platforms 

---

Runtime/Scripts/RTCPeerConnection.cs

RTCPeerConnection throws KeyNotFoundException below when firing the callback after disposing the its instance. 
```
KeyNotFoundException: The given key was not present in the dictionary. at 
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00000] in 
<00000000000000000000000000000000>:0 at Unity.WebRTC.RTCPeerConnection.FindObserver[T] (System.IntPtr ptr) [0x00000] 
in <00000000000000000000000000000000>:0 at Unity.WebRTC.WebRTC+<>c__DisplayClass32_0.
<OnSetRemoteDescription>b__0 () [0x00000] in <00000000000000000000000000000000>:0 at 
Unity.WebRTC.WebRTC.SendOrPostCallback (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 at 
Unity.WebRTC.ExecutableUnitySynchronizationContext+WorkRequest.Invoke () [0x00000] in …
```

fix: Fix KeyNotFoundException in RTCPeerConnection

---

Plugin~/WebRTCPlugin/VideoFrameAdapter.cpp

We found the issue that occurring crash on specific Android devices like Pixel4a when streaming high resolution video.
We got the crash log below.
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2020.3.43f1 (75bff06b76bf)', Build type 'Development', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
Build fingerprint: 'google/sunfish/sunfish:13/TP1A.220905.004/8927612:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2022-12-23 10:34:43+0900
pid: 28577, tid: 28626, name: UnityGfxDeviceW  >>> com.DefaultCompany.RenderStreaming <<<
uid: 10385
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xfb20507950
x0  b400007ba0676a90  x1  000000000000000a  x2  b400007b004b7510  x3  0000000000000001
x4  000000000000002e  x5  0000000000000002  x6  00000007fe35fa30 …
```

fix: Fix crash on Android device Pixel4a

---

CHANGELOG.md
Plugin~/WebRTCPlugin/GpuMemoryBufferPool.cpp
Plugin~/WebRTCPlugin/GpuMemoryBufferPool.h
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalTexture2D.h
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalTexture2D.mm
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPluginTest/GpuMemoryBufferPoolTest.cpp

This PR fixes memory leak on macOS/iOS.
Fix this issue https://github.com/Unity-Technologies/com.unity.webrtc/issues/868
First, fixed the issue of the reference counter of Objective-C. It is needed to call release message explicitly.
```
[m_texture release];
```
Second, the buffer pool should be set the limit of number of creating buffer. Currently the limit number is set 10 which should be enough in this situation.

fix: Fix memory leak on macOS/iOS when streaming high resolution video

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp
Plugin~/WebRTCPlugin/GpuMemoryBuffer.cpp
Plugin~/WebRTCPlugin/GpuMemoryBuffer.h
Plugin~/WebRTCPlugin/GpuMemoryBufferPool.cpp
Plugin~/WebRTCPlugin/VideoFrameAdapter.cpp
Tests/Runtime/StatsReportTest.cs
Tests/Runtime/VideoReceiveTest.cs

This PR below didn't improve the crash issue.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/867
I reverted the previous changes and I checked the issue carefully, and found the cause of the issue is the status of fences for managing copy texture.
We needed to consider the error processing when the fence is unintended status. The PR changes not using the texture if the fence is failed to reset its signal.

fix: Fix crash on Android pixel4a with vulkan

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp

How to reproduce:
- This issue cannot be consistently reproduced. We are seeing NVENCException's occur during init and reconfigure calls infrequently, and the logged parameters are valid.
- The following is the exception message from a crash, "terminating with uncaught exception of type NVENCException: Reconfigure : m_nvenc.nvEncReconfigureEncoder(m_hEncoder, const_cast<NV_ENC_RECONFIGURE_PARAMS*>(pReconfigureParams)) returned error 8 at com.unity.webrtc/Plugin~/NvCodec/NvCodec/NvEncoder/NvEncoder.cpp:522"
Expected behavior:
- Application won't crash, and will log errors when encoder encounters issues.
How this was tested:
- Ran unit tests / build pipeline.
- Tested application manually.

fix: fix unhandled NVENCException's occuring during initialization & reconfigure calls

---

Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Runtime/Scripts/Context.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/NativeAPITest.cs

Issue:
Graphics native plugins can reserve an event range to use when issuing their custom events.
Reserving a range allows the plugin to configure their own events and is useful to ensure there is no overlap with other plugins.
Currently, the WebRTC plugin isn't configuring it's own events, and is issuing an event with ID 0. 
This is an issue, as WebRTC should be configuring it's render event to ensure it's excuted outside the render pass, and since it's using a non-reserved ID, any other native graphics plugin could be using the same ID, and configuring it with the wrong settings.
Summary of changes:
This change adds reserving a range of events to use, configuring the events, pushing the eventID through the API, updating unit tests, and checking that events issued have the expected …

Add reserving eventID range and vulkan configuration for custom plugin events

---

Plugin~/WebRTCPlugin/UnityRenderEvent.cpp

This simple check makes sure that vulkan is actually available and not a nullptr.
It enables dedicated servers to at least run the preload and not crash in the process of running webrtc without graphics initialized.
I didnt test yet to which degree webrtc feature works, but the Audio WebRtc Testscene works now without crash.
Fixes #791 in my case at least.
The reason this crashed is that vulkan is not available on dedicated server build and this function returns a nullptr which is not handled:
https://github.com/Unity-Technologies/com.unity.webrtc/blob/main/Plugin%7E/WebRTCPlugin/UnityVulkanInterfaceFunctions.cpp#L17

Fix: Fix Crash on dedicated Linux Server

---

Plugin~/WebRTCPlugin/GpuMemoryBuffer.cpp
Plugin~/WebRTCPlugin/GpuMemoryBuffer.h
Plugin~/WebRTCPlugin/GpuMemoryBufferPool.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/VideoFrameUtil.cpp

This PR fixes the performance issue of video streaming when using vulkan graphics API on Linux with Unity 2022.2.
This issue is able to replicated by this condition below.
- Ubuntu 20.04
- Unity 2022.2 (Unity 2022.1 works fine)
- Use the samples of Unity Render Streaming
- Stream a video from Broadcast sample and receive a video streaming on Browser
- Any video codecs
- Build runtime (Not reproduced the issue on Unity Editor)
- Vulkan graphics API
The cause of this issue is handling errors occurred by vulkan synchronization between GPU and CPU. In addition, The timing of accessing rendering queue is another reason. We fixed the timing with callback of `UnityVulkanInterface::AccessQueue`.

fix: Change UnityVulkanPluginEventConfig parameters for vulkan API

---

Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Samples~/Encryption.meta
Samples~/Encryption/Encryption.unity
Samples~/Encryption/Encryption.unity.meta
Samples~/Encryption/EncryptionSample.cs
Samples~/Encryption/EncryptionSample.cs.meta
Samples~/Menu/Menu.unity
Samples~/Metadata/MetadataSample.cs
Samples~/Scripts/SceneSelectUI.cs
WebRTC~/ProjectSettings/EditorBuildSettings.asset

This pull requests fixes bugs of "metadata" sample witch is for demonstrating Encoded Transform. Previous implementation works VP8/VP9 codecs but not H264/AV1 codec. The issue of H264 codec has already fixed. However, The issue of AV1 codec is remained.
When using Encoded Transforrm API, replacing frame data has a limitation which we should not replace the first couple of bytes of the payload. For example, In [this script](https://github.com/webrtc/samples/blob/gh-pages/src/content/insertable-streams/endtoend-encryption/js/worker.js#L19) in the official webrtc sample repository contains comments about this limitation.
In addition, this pull request adds a "Encrypt" sample which shows a simple implementation of end-to-end encryption using Encoded Transform API. …

fix: Fix Encoded Transform samples

---

Plugin~/WebRTCPlugin/Codec/NvCodec/NvDecoderImpl.cpp

This PR fixes the crash when replacing video track with NvCodec.
This issue is caused by [this change](https://github.com/Unity-Technologies/com.unity.webrtc/pull/860/files#diff-598391271633935bfe3e5bffaa64de9b76171b1639eb21bb904dbb2ab3c293eeR706-R708). At a glance, it is only upgrading NvCodec SDK. however, this contained changing order of NvDecoder constructor's argumenets, that's why always `m_nMaxHeight` is zero. The first time of evaluating this parameter is replacing video track.

fix: Fix a runtime error when replacing track with NvCodec

---

Plugin~/WebRTCPlugin/Logger.cpp
Runtime/Scripts/RTCRtpTransform.cs

This is workaround for Android platform. 
Add an attribute `MethodImpl(MethodImplOptions.NoOptimization)` to **RTCEncodedFrame.GetData** method to avoid a crash issue.

fix: Fix Workaround for a crash issue that EncodedTransform APIs on Android platform 

---

Plugin~/WebRTCPlugin/GpuMemoryBuffer.cpp
Plugin~/WebRTCPlugin/GpuMemoryBufferPool.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.h
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/GpuMemoryBufferCudaHandle.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/GpuMemoryBufferCudaHandle.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp

Mostly just code cleanups for CUDA handling, but should fix resource leaks for D3D12/Vulkan that use mipmappedArray. M92 era branch used to handle calling cuMipmappedArrayDestroy
Can't be sure if this alone fixes all the leaks I've seen, as I'm still using custom frame pooling, scheduling and vulkan changes on my branch, but have to start from somewhere.

Fix cuda resource leak

---

Plugin~/WebRTCPlugin/CMakeLists.txt
Plugin~/WebRTCPluginTest/CMakeLists.txt

This issue is reported from users below.
#892
#906
This PR use CMake command `target_precompile_headers` which is supported since CMake 3.16.

fix: Fix MSVC compiler support on CLion

---

Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Runtime/Scripts/Context.cs
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Tests/Runtime/NativeAPITest.cs
Tests/Runtime/VideoReceiveTest.cs

I've had some use cases where I'm dealing with multiple recv/send video tracks and it's hard to profile how much time is spent in total when there's multiple command buffer submissions. It'll save some main/render thread processing time if we just submit the requests in batches. If needed to, you could do "once a frame" bookkeeping on the native side, flush, etc.
- Add `WebRTC` label for command buffer
- CPU texture updates through standard Unity plugin interface are simple and ok, but it doesn't scale if you need more performance or deal with multiple tracks. Lay out small groundwork for doing texture updates manually, but the actual changes to video renderer and GraphicsDevice will need to wait another day :) Basically it's uploading to CPU staging texture off render thread and only …

Command buffer batching

---

Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12Texture2D.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12Texture2D.h

In the past, DX12 graphics device accessed the legacy interface to ensure the compatibility. 
However, we have already changed the process about DX12 resources, therefore these were not needed.

refactor: Remove accessing the legacy interface in DX12

---

Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11Texture2D.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11Texture2D.h

This pull request improves the performance of the rendering thread which caused by the waiting time for rendering commands to copy render textures.
The past implementation is waiting the `ID3D11DeviceContext::Flush` to wait completion of rendering process, therefore it increases the load on rendering thread. In this change, by using `ID3D11Fence` to wait GPU process on the worker thread, it decreases the load on the rendering thread.
Currently, we are developing the same change for D3D12.

performance: Use fence to sync between GPU/CPU in D3D11

---

Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12Texture2D.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12Texture2D.h
Plugin~/WebRTCPluginTest/FrameGenerator.cpp
Plugin~/WebRTCPluginTest/GraphicsDeviceTest.cpp

Related this PR.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/923
This PR fixes the native code of DX12 graphic device to improve performance of the rendering thread. I profiled the loads of the rendering thread, and compared two results. This comparison can show the performance improvement that reduces the loads of waiting time for command buffer to copy texture.
Before
After
We will deal with other graphics device Metal and GLCore near future.

performance: Use fence to sync GPU/CPU when using D3D12

---

Runtime/Scripts/AudioStreamTrack.cs
Tests/Runtime/AudioStreamTrackTest.cs
Tests/Runtime/TransceiverTest.cs

**AudioStreamTrack.SetData** is not able to called from the worker thread.
This PR adds **public void SetData(ReadOnlySpan<float> span, int channels, int sampleRate)** to set audio buffer from the worker thread.

fix: Support calling AudioStreamTrack.SetData on worker thread

---

Editor/BuildProcessor.cs

**AndroidSdkVersions.AndroidApiLevel22** is already obsoleted on Unity2020.3 LTS.

fix: Change android minimum level because the api level is obsoleted

---

Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.h

The command buffer allocator should be reset once in one frame.
According to [the API document](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12commandallocator-reset):
> Unlike [ID3D12GraphicsCommandList::Reset](https://learn.microsoft.com/en-us/windows/desktop/api/d3d12/nf-d3d12-id3d12graphicscommandlist-reset), it is not recommended that you call Reset on the command allocator while a command list is still being executed.
In [the last PR](https://github.com/Unity-Technologies/com.unity.webrtc/pull/924), the copy texture process was changed asyncnous. This is no problem when using one video source. However, it is failed by using multiple video sources.

fix: Reset command buffer allocator once in one frame in DX12

---

Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.h

There is a previous fix here. 
https://github.com/Unity-Technologies/com.unity.webrtc/pull/939
**ID3D12CommandAllocator::Reset** should not be called before the command execution is complete. However, if only one ID3D12CommandAllocator is used, the previous command may not be completed in time. 
This fix uses multiple ID3D12CommandAllocator so that the ID3D12CommandAllocator in use is not discarded.

fix: Fix crash when sending videos from multiple peers with DX12

---

Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.mm
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalTexture2D.h
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalTexture2D.mm

This is a performance optimization fix for Metal.
Previously, when copying textures for video transmission, [MTLCommandBuffer::waitUntilCompleted](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1443039-waituntilcompleted?language=objc) was used to detect when the texture copy command was finished. Since this method is called on the rendering thread, it could cause subsequent graphics-related operations to block.
This fix uses [MTLCommandBuffer::addCompletedHandler](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1442997-addcompletedhandler?language=objc) and semaphores to implement the wait process. It waits for the semaphore's signal on the worker thread, the load on the rendering thread is reduced.
Refer to [this …

performance: Use semaphore to wait command buffer completion on macos/ios

---

Plugin~/WebRTCPlugin/Logger.cpp
Plugin~/WebRTCPlugin/PeerConnectionObject.cpp
Plugin~/WebRTCPlugin/UnityLogStream.cpp
Plugin~/WebRTCPlugin/UnityLogStream.h
Plugin~/WebRTCPlugin/WebRTCPlugin.h
Plugin~/WebRTCPlugin/pch.h
Runtime/Scripts/WebRTC.cs
Tests/Runtime/ContextTest.cs
Tests/Runtime/MockLogger.cs
Tests/Runtime/MockLogger.cs.meta
Tests/Runtime/WebRTCTest.cs

Description of changes:
- Added configurable logger to WebRTC to enable users to customize logging for their environment.
- Added API to allow for configuring native logging.
- Updated logging inside the package to use the settable logger instead of the built in Unity logging.
How this was tested:
- Tested by running the WebRTC package tests & Native tests.
- Ran through the package samples to ensure it's working properly with and without a new logger set.

feat: Add configurable logger

---

.yamato/format.yml
.yamato/nativeplugin.yml
.yamato/upm-ci-libwebrtc.yml
.yamato/upm-ci-webrtc-packages.yml
BuildScripts~/build_plugin_linux.sh
BuildScripts~/build_plugin_win.cmd
BuildScripts~/build_testrunner_linux.sh
BuildScripts~/build_testrunner_win.cmd
Plugin~/CMakeLists.txt
Plugin~/NvCodec/CMakeLists.txt
Plugin~/NvCodec/Utils/ResizeSurf.cu
Plugin~/NvCodec/Utils/ResizeSurf.h
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.h
Plugin~/WebRTCPluginTest/FrameGenerator.cpp

- Add CUDA kernel for scaling down texture resolution.
- Add **enable_language(CUDA)** in CMakeLists.txt to build CUDA kernel.
- Upgrade **CUDA Toolkit 11.6**, CUDA supports VS2022 since 11.6. 
- Change **msvc** compiler for windows plugin because **clang-cl** is not worked with CUDA compiler.

fix: Support scale resolution for h264 codec

---

Documentation~/tutorial.md

Updating the variable name for the send channel var `channel` which I assume is meant to be `sendChannel` based on initialization.

Fix var name typo in tutorial.md

---

Plugin~/WebRTCPlugin/GraphicsDevice/CMakeLists.txt
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/GpuMemoryBufferCudaHandle.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11Texture2D.h
Plugin~/WebRTCPlugin/GraphicsDevice/IGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/ScopedGraphicsDeviceLock.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/ScopedGraphicsDeviceLock.h
Plugin~/WebRTCPluginTest/GraphicsDeviceContainer.cpp

I was doing some testing on PC with Unity editor, though I'm mostly using Vulkan.
I ran into occasional crash issue with D3D11 where the device gets lost and no matter what I did, couldn't repro it with other graphics apis. Someone else had similar issue at https://forums.developer.nvidia.com/t/d3d11-device-context-in-a-separate-thread-gets-corrupted-when-cuda-graphics-resource-mapping-is-used/232326 and luckily applying similar locking fixed the issue for me
I don't recall seeing this issue before, but seems the chances of this happening started after the recent fence change

Fix: Cuda thread safety with D3D11

---

Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLTexture2D.h

This PR improves a CPU load of Render thread when using video encoding with OpenGL or GLES. 
It uses **GLSync** instead of **glFinish**  to sync GPU and CPU.
Specifically, the process time of **UnityVideoTrackSource.OnFrameCaptured** is dramatically reduced.

performance: Use GLsync to wait commandbuffer GPU process on GLCore/GLES

---

Plugin~/WebRTCPlugin/UnityVideoTrackSource.cpp
Plugin~/WebRTCPlugin/UnityVideoTrackSource.h
Plugin~/WebRTCPlugin/VideoFrameScheduler.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Plugin~/WebRTCPluginTest/VideoTrackSourceTest.cpp
Runtime/Scripts/RTCRtpSender.cs
Runtime/Scripts/VideoStreamTrack.cs
Runtime/Scripts/WebRTC.cs
Samples~/Bandwidth/BandwidthSample.cs
Samples~/E2ELatency/E2ELatency.unity
Samples~/E2ELatency/E2ELatencySample.cs

This implements Frame synchronization mode.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/803

performance: RTCRtpSender.SyncApplicationFramerate

---

.yamato/package.metafile
BuildScripts~/build_libwebrtc_android.sh
BuildScripts~/build_libwebrtc_ios.sh
BuildScripts~/build_libwebrtc_linux.sh
BuildScripts~/build_libwebrtc_macos.sh
BuildScripts~/build_libwebrtc_win.cmd
BuildScripts~/build_plugin_android.sh
BuildScripts~/build_plugin_ios.sh
BuildScripts~/build_plugin_linux.sh
BuildScripts~/build_plugin_mac.sh
BuildScripts~/build_plugin_win.cmd
BuildScripts~/build_testrunner_android.sh
BuildScripts~/build_testrunner_linux.sh
BuildScripts~/build_testrunner_mac.sh
BuildScripts~/build_testrunner_win.cmd
BuildScripts~/patches/fetch_exclude_examples.patch
BuildScripts~/test_plugin_android.sh
BuildScripts~/test_plugin_ios.sh
Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.cpp
Plugin~/WebRTCPluginTest/NvCodec/NvCodecTest.cpp
Plugin~/WebRTCPluginTest/NvCodec/NvEncoderImplTest.cpp
README.md
Runtime/Scripts/RTCStats.cs
Tests/Runtime/StatsReportTest.cs

The previous update of libwebrtc is here. 
https://github.com/Unity-Technologies/com.unity.webrtc/pull/960
However, building libwebrtc is failed because of android_toolchain in third_party folder in Chromium. We got the error below.
```
Traceback (most recent call last):
File "/home/bokken/build/output/Unity-Technologies/com.unity.webrtc/depot_tools/metrics.py", line 296, in print_notice_and_exit
yield
File "/home/bokken/build/output/Unity-Technologies/com.unity.webrtc/depot_tools/gclient.py", line 3770, in <module>
sys.exit(main(sys.argv[1:]))
File "/home/bokken/build/output/Unity-Technologies/com.unity.webrtc/depot_tools/gclient.py", line 3756, in main
return dispatcher.execute(OptionParser(), argv)
File "/home/bokken/build/output/Unity-Technologies/com.unity.webrtc/depot_tools/subcomman …
```

feat: libwebrtc m116

---

Runtime/Scripts/VideoStreamTrack.cs

When I added support for "VUZIX M400 SMART GLASSES" to the project, the picture from the glasses was diagonally flipped. So I added the horizontal and diagonal flip.
```
videoStreamTrack = new VideoStreamTrack(webCamTexture, false, true); //Flip horizontaly
sourceRawImage.uvRect = new Rect(1, 1, -1, -1); //Flip diagonally for display
```

feat: Added support for horizontal flip sourceTexture

---

Plugin~/WebRTCPlugin/VideoFrameAdapter.cpp

- #890
The VP8 encoder on macOS calls `ScaledBuffer::CropAndScale`, so it have to be implemented.

fix: Implement VideoFrameAdapter::ScaledBuffer::CropAndScale

---

Plugin~/WebRTCPlugin/Codec/CreateVideoCodecFactory.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Cuda/CudaContext.cpp

Some CUDA platforms do not support NvEncoder, so using the relevant API without confirmation will cause a crash.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/806
I referred to Nvidia's GitHub project, we can see that it checks for DLLs before calling NvEncoder APIs. 
https://github.com/NVIDIA/video-sdk-samples/blob/aa3544dcea2fe63122e4feb83bf805ea40e58dbe/Samples/NvCodec/NvEncoder/NvEncoder.cpp#L58

fix: checks for DLLs before calling NvEncoder APIs

---

Plugin~/WebRTCPlugin/GpuMemoryBuffer.cpp
Plugin~/WebRTCPlugin/UnityVideoRenderer.cpp
Tests/Runtime/VideoReceiveTest.cs

This is a revert commit to fix a video rendering issue which occurs when using the WebRTC package for Unity Render Streaming.
The previous PR is #966.
- #966
Applicable parts is here.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/966/files#diff-bd9da9905e2651e2f1924415998c4a3d6545dcf51a4441e27fcc567e376e6464
https://github.com/Unity-Technologies/com.unity.webrtc/assets/1132081/a612057a-6dbe-4771-8026-55f211e814fb
I checked Android and Windows with Vulkan graphic API.

fix: Revert change of GpuMemoryBuffer to fix video rendering issue

---

Runtime/Scripts/AudioStreamTrack.cs

I'm experiencing a rare audio related crash, maybe once a month. Either in the player or the editor when the whole application is being shut down.
I do have some other audio changes on plugin side that made the issue less likely, but right now it feels like this C# side code ordering change should be good to apply regardless.
```
=================================================================
Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
=================================================================
Managed Stacktrace: …
```

fix: rare audio crash during shutdown

---

BuildScripts~/build_libwebrtc_android.sh
BuildScripts~/build_libwebrtc_ios.sh
BuildScripts~/build_libwebrtc_linux.sh
BuildScripts~/build_libwebrtc_macos.sh
BuildScripts~/build_libwebrtc_win.cmd
BuildScripts~/patches/libvpx_vp8_encoder.patch

This crash is occurred by `SetRawImagePlanes` in [libvpx_vp8_encoder.cc](https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/modules/video_coding/codecs/vp8/libvpx_vp8_encoder.cc).
I created a patch file to avoid null pointer exception in the VP8 encoder.
Related issue.
- #993

fix: Fix crash on Android when using VP8 encoder

---

Plugin~/WebRTCPlugin/Context.cpp
Plugin~/WebRTCPlugin/GpuMemoryBuffer.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/CMakeLists.txt
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/GraphicsUtility.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/GraphicsUtility.h
Plugin~/WebRTCPlugin/GraphicsDevice/ITexture2D.h
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.mm
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanTexture2D.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanTexture2D.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanUtility.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanUtility.h
Plugin~/WebRTCPlugin/UnityRenderEvent.cpp
Plugin~/WebRTCPlugin/UnityVideoDecoderFactory.cpp
Plugin~/WebRTCPlugin/UnityVideoEncoderFactory.cpp
Plugin~/WebRTCPlugin/UnityVideoRenderer.cpp
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp

related PR #975.
This PR is reverted this #967. I'm sorry to revert this which is efforted by @aet.
We are currently in the QA phase of package development and have tested and confirmed the issue under the following conditions:
- Use the Vulkan Graphic API
- Set Graphics Job enabled in Player Settings Window
- Build the native plugin for Release, not Debug
- Turn off Development Build in Build Settings Window
When testing video streaming with the PeerConnection sample, no video is received.
This issue is occurring since the https://github.com/Unity-Technologies/com.unity.webrtc/commit/665ad1ff2a9d6f113fda95d630249e29cae0970e. We have also confirmed that enabling **VULKAN_USE_CRS** resolves the issue. However, there is another problem when VULKAN_USE_CRS is enabled: performance may be …

fix: Revert: Vulkan CPU texture read performance, improve Unity pipeline state integration

---

BuildScripts~/build_libwebrtc_android.sh
BuildScripts~/patches/fix_android_videoencoder.patch

This patch fixes the crash of [`NativeToJavaVideoFrame`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/sdk/android/src/jni/video_frame.cc;l=291?q=NativeToJavaVideoFrame&ss=chromium%2Fchromium%2Fsrc) in `video_frame.cc`.
```
#00 pc 0000000000394d9c  /data/app/com.DefaultCompany.sample-bK3oa2WEYI7iWytdp1Ujlw==/lib/arm64/libwebrtc.so (webrtc::jni::WrapI420Buffer(_JNIEnv*, rtc::scoped_refptr<webrtc::I420BufferInterface> const&)+60)
#01 pc 00000000003941ac  /data/app/com.DefaultCompany.sample-bK3oa2WEYI7iWytdp1Ujlw==/lib/arm64/libwebrtc.so (webrtc::jni::NativeToJavaVideoFrame(_JNIEnv*, webrtc::VideoFrame const&)+108)
#02 pc 0000000000391240  /data/app/com.DefaultCompany.sample-bK3oa2WEYI7iWytdp1Ujlw==/lib/arm64/libwebrtc.so …
```

fix: Add a patch to fix Android crash when stopping video track

---

Plugin~/WebRTCPlugin/GpuMemoryBuffer.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D11/D3D11GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/D3D12/D3D12GraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/GraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/IGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Metal/MetalGraphicsDevice.mm
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/OpenGL/OpenGLGraphicsDevice.h
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.cpp
Plugin~/WebRTCPlugin/GraphicsDevice/Vulkan/VulkanGraphicsDevice.h
Plugin~/WebRTCPlugin/WebRTCPlugin.cpp
Runtime/Scripts/WebRTC.cs
Tests/Runtime/WebRTCTest.cs

Description of changes:
- Added configurable graphics sync timeout to allow consumers to specify timeout.
How this was tested:
- Tested by running the WebRTC package tests & Native tests.
- Ran through the package samples to ensure it's working properly.

feat: add configurable graphics sync timeout

---

Plugin~/WebRTCPlugin/Codec/CreateVideoCodecFactory.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.cpp
Plugin~/WebRTCPlugin/Codec/NvCodec/NvCodec.h
Plugin~/WebRTCPluginTest/NvCodec/NvCodecTest.cpp

Even on Nvidia devices that support CUDA, NvEncAPI may not be available. (ex MX450)
refer https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new
On those devices, the DLLs (nvcuda.dll, nvencodeAPI.dll) can be found, but an error will occur when calling the open session API.
Therefore, check whether you can open Session and determine whether NvEnc can be used on that device.
I think fix this https://github.com/Unity-Technologies/com.unity.webrtc/issues/806
maybe fix this https://github.com/Unity-Technologies/com.unity.webrtc/issues/1006

Fix: Crash on the device that does not support NvEnc API .

---

.yamato/package.metafile
.yamato/upm-ci-webrtc-packages.yml
BuildScripts~/build_libwebrtc_android.sh
BuildScripts~/build_plugin_android.sh
BuildScripts~/build_plugin_ios.sh
BuildScripts~/build_plugin_linux.sh
BuildScripts~/build_plugin_mac.sh
BuildScripts~/build_plugin_win.cmd
BuildScripts~/build_testrunner_android.sh
BuildScripts~/build_testrunner_linux.sh
BuildScripts~/build_testrunner_mac.sh
BuildScripts~/build_testrunner_win.cmd
BuildScripts~/patches/README.md
BuildScripts~/patches/support_16kb_pagesizes_android.patch
BuildScripts~/test_plugin_android.sh
BuildScripts~/test_plugin_ios.sh
CHANGELOG.md
README.md

This pull request updates the WebRTC package to add support for 16 KB page sizes on 64-bit Android devices and bumps the libwebrtc binaries to a new release. The changes ensure compliance with Google Play requirements for Android 15+ and update documentation and CI configurations accordingly ([detail](https://developer.android.com/guide/practices/page-sizes#windows-powershell_2)).
**Android 16 KB page size support:**
* Added a new patch (`support_16kb_pagesizes_android.patch`) and applied it in the Android build script to set linker flags for 16 KB page sizes in `libjingle_peerconnection_so.so` (`BuildScripts~/build_libwebrtc_android.sh`, `BuildScripts~/patches/support_16kb_pagesizes_android.patch`, `BuildScripts~/patches/README.md`). …

feature: Support 16kb pagesizes for Android 

---

.yamato/nativeplugin.yml
.yamato/upm-ci-webrtc-packages.yml
BuildScripts~/build_plugin_android.sh
BuildScripts~/build_plugin_ios.sh
BuildScripts~/build_plugin_linux.sh
BuildScripts~/build_plugin_mac.sh
BuildScripts~/build_plugin_win.cmd

This pull request introduces support for building native plugins in both debug and release modes across all supported platforms. The build scripts and CI configuration files have been updated to allow specifying the build type, and dependencies have been adjusted to use the correct build artifacts for packaging and deployment.
**Build System Enhancements:**
* Added support for both debug and release build types in the CI configuration (`.yamato/nativeplugin.yml`). Each platform now builds both variants, and build jobs are parameterized by build type.
* Updated CI dependencies in `.yamato/nativeplugin.yml` and `.yamato/upm-ci-webrtc-packages.yml` to reference only the release build artifacts for packaging and plugin publishing steps. …

ci: Support debug build native plugins with arguments of build scripts 
